import thekua from "../../assets/thekua.png";
import aloobhujiya from "/src/assets/aloo_bhujiya.png";
import baiganbhaja from "/src/assets/baigan_bhaja.png";
import balushai from "/src/assets/balushai.png";
import bhakka from "/src/assets/bhakka.png";
import chana_chat from "/src/assets/chana_chat.png";
import chana_muri from "/src/assets/chana_muri.png";
import chandrakala from "/src/assets/chandrakala.png";
import chicken_chawal from "/src/assets/chicken_chawal.png";
import dahi_chuda from "/src/assets/dahi_chuda.png";
import fry_chida from "/src/assets/fry_chida.png";
import handi_mutton from "/src/assets/handi_mutton.png";
import jhalmuri from "/src/assets/jhalmuri.png";
import khichdi from "/src/assets/khichdi.png";
import machi_chawal from "/src/assets/machi_chawal.png";
import malpua from "/src/assets/malpua.png";
import rasgulla from "/src/assets/rasgulla.png";
import sattu_paratha from "/src/assets/sattu_paratha.png";
import sewai from "/src/assets/sewai.png";
import sheer_khurma from "/src/assets/sheer_khurma.png";
import litti_chokha from "/src/assets/litti.jpg";


const foodData = [
  {
    id: 1,
    title: "Litti Chokha",
    image: litti_chokha,
    short:
    "Litti Chokha is a traditional and popular dish of Kishanganj that reflects the authentic food culture of Bihar. Made from whole wheat flour stuffed with spiced roasted gram flour (sattu) and served with mashed vegetables like brinjal, potato, and tomato, this dish is loved for its earthy flavor, simplicity, and nutritional value. It is deeply connected to the rural lifestyle and everyday meals of the region. The slow roasting gives it a smoky and rustic aroma. It is often enjoyed with desi ghee for extra richness. Litti-Chokha represents the soul of Bihari cuisine.",
    full:
    "Litti-Chokha is one of the most iconic traditional dishes associated with Kishanganj and the Bhojpuri region of Bihar. This dish represents the simplicity, tradition, and rural lifestyle of the region. Litti is prepared from whole wheat flour dough balls stuffed with a flavorful mixture of roasted gram flour (sattu), mustard oil, garlic, ginger, green chilies, and traditional spices. It is traditionally roasted over charcoal or a clay stove, which gives it a unique smoky aroma and taste. Chokha is served as a side dish and is made by mashing roasted brinjal, boiled potatoes, and fresh tomatoes with mustard oil, onions, garlic, green chilies, and herbs. When served together, Litti and Chokha form a wholesome and balanced meal. A topping of desi ghee further enhances the richness and flavor of the dish. In Kishanganj, Litti-Chokha is more than just a meal—it is a cultural symbol passed down through generations. It is commonly enjoyed during festivals, family gatherings, village fairs, and daily meals. Due to its high nutritional value and long shelf life, it has historically been a favorite among farmers and travelers. Today, Litti-Chokha has gained popularity beyond Bihar and is recognized as an important part of Indian traditional cuisine.",
  },
  {
    id: 2,
    title: "Thekua",
    image: thekua,
        short:
    "Thekua is a traditional sweet delicacy of Bihar, widely prepared in regions like Kishanganj. Made from wheat flour, jaggery, and ghee, Thekua is deep-fried until crisp and golden. It is best known as the sacred Prasad of Chhath Puja and symbolizes purity, devotion, and ancient Indian food traditions. It has a long shelf life and natural sweetness. Thekua carries religious and cultural importance. It is made without artificial ingredients. It reflects the purity of traditional cooking.",
    full:
    "Thekua is one of the most ancient and culturally significant traditional sweets of Bihar, especially popular in Kishanganj, eastern Uttar Pradesh, Jharkhand, and the Terai region of Nepal. Prepared using whole wheat flour, jaggery (or honey), ghee, and sometimes dry fruits, Thekua is shaped using wooden molds and deep-fried until it becomes crisp on the outside and firm inside. Its rich aroma, long shelf life, and natural ingredients make it ideal for religious offerings. The history of Thekua is believed to be over 3,000 years old, tracing back to the Vedic period. Ancient texts like the Rigveda mention a sweet dish called “Apupa”, which closely resembles modern-day Thekua in both ingredients and preparation. Apupa was offered to deities during Vedic rituals and was considered a nourishing and sacred food. Over time, this ancient dish evolved regionally and came to be known as Thekua. The name Thekua is believed to have originated from the word “thokna” (to press or pound), as the dough was traditionally pressed firmly into wooden molds before frying. This method gave Thekua its distinct shape and design. Thekua holds a very special place in Chhath Puja, where it is offered as Mahaprasad to the Sun God (Surya Dev) and Chhathi Maiya. Since it is prepared without onion, garlic, or artificial ingredients, it is considered pure and spiritually auspicious. In Bihari households, preparing Thekua during Chhath is an act of devotion, discipline, and faith passed down through generations. Today, Thekua is not only a religious offering but also a beloved traditional snack enjoyed with tea. Rich in energy due to jaggery and ghee, it represents the simplicity, sustainability, and deep-rooted cultural heritage of Bihar.",
  },
   {
    id: 3,
    title: "Baigan bhaja",
    image: baiganbhaja,
    short:
    "Baigan Bhaja, also known as Begun Bhaja, is a traditional fried brinjal dish popular in Kishanganj and eastern India. Made with sliced eggplant, simple spices, and mustard oil, it is loved for its crispy texture and smoky flavor. This timeless dish has been prepared in home kitchens for generations, representing the agrarian lifestyle where seasonal vegetables were transformed into satisfying meals. Served with rice and dal, it represents the beauty of minimal and traditional Indian home cooking, showcasing how simple ingredients can create extraordinary flavors.",
    full:
    "Baigan Bhaja, known as Begun Bhaja in Bengali, literally means “fried brinjal” and is one of the most traditional and timeless vegetable dishes of eastern India. In regions like Kishanganj, where Bihari and Bengali food cultures naturally blend, this dish has been prepared in home kitchens for generations. Its history is deeply rooted in agrarian life, where simple, seasonal vegetables were transformed into satisfying meals using minimal ingredients. Brinjal (eggplant) has been cultivated in the Indian subcontinent for thousands of years, and frying sliced vegetables was among the earliest cooking techniques practiced in rural households. Baigan Bhaja emerged as a practical and flavorful dish that required only basic spices such as salt, turmeric, and red chili powder. Over time, mustard oil became an essential ingredient in eastern India, giving the dish its signature pungent aroma and smoky taste. Traditionally, thick slices of brinjal are lightly marinated with spices and shallow-fried until the outer skin becomes crisp while the inside turns soft and buttery. The slightly charred peel adds a smoky depth that defines the dish. In many households, Baigan Bhaja is enjoyed with plain rice and dal, making it a complete and comforting meal despite its simplicity. In Bengali kitchens, Begun Bhaja is considered one of the most quintessential comfort foods, often served at the beginning of a traditional meal. In Kishanganj and Bihar, it is equally valued for its homely taste and affordability. Variations exist across regions—some add dried mango powder for tanginess, some lightly coat the slices with flour or semolina—but the heart of the dish remains unchanged: letting the natural flavor of brinjal shine. Baigan Bhaja is more than just a fried vegetable dish; it reflects an ancient food philosophy where taste, nutrition, and simplicity are perfectly balanced. Even today, it continues to hold a special place in everyday meals, reminding people of traditional kitchens, slow cooking, and the cultural richness of eastern Indian cuisine.",
  },
   {
    id: 4,
    title: "Balushai",
    image: balushai,
    short:
    "Balushahi, also known as Makhan Bada or Badusha, is a traditional Indian sweet widely enjoyed in Kishanganj and across Bihar. Made from maida, ghee, and sugar syrup, it is known for its crisp outer layer and soft, flaky center. This classic dessert has been prepared using simple yet rich ingredients for generations, reflecting traditional Indian sweet-making techniques. Balushahi is commonly prepared during festivals and special occasions, symbolizing celebration, prosperity, and hospitality in Indian culture.",
    full:
    "Balushahi, also called Makhan Bada, Balusaahi, or Badusha, is a classic dessert that originated in the Indian subcontinent. It holds a special place in the traditional sweet culture of Bihar, including regions like Kishanganj, as well as parts of North and South India. In South India, a similar sweet is known as Badusha. Historically, Balushahi developed using simple yet rich ingredients such as refined flour (maida), ghee or makhan (butter), and sugar. The slow deep-frying process in ghee followed by dipping in sugar syrup reflects traditional Indian sweet-making techniques passed down through generations. Unlike doughnuts, Balushahi has a unique flaky texture and a dense yet soft interior. In Kishanganj and nearby areas, Balushahi is closely associated with festivals, weddings, and religious celebrations. It is often prepared in advance and shared with guests as a symbol of happiness, prosperity, and hospitality. Local sweet shops take pride in preparing Balushahi using traditional methods to maintain its authentic taste. Culturally, Balushahi represents celebration and togetherness. Its rich flavor and long shelf life made it a preferred sweet during journeys and festive gatherings in earlier times. Even today, despite the popularity of modern desserts, Balushahi continues to be loved for its traditional taste and cultural value. Balushahi remains an important part of Bihar’s sweet heritage, connecting people to their roots through its timeless preparation, rich aroma, and festive charm.",
  },
   {
    id: 5,
    title: "Bhakka",
    image: bhakka,
    short:
    "Bhakka is a traditional steamed rice delicacy popular in Kishanganj, Seemanchal, and neighboring regions of Nepal. Made from freshly ground rice flour and cooked by steaming, Bhakka is soft, healthy, and naturally flavorful. This gentle cooking method preserves both the natural taste and nutritional value of rice, making it suitable for all age groups. It is commonly enjoyed with chutney, curd, or jaggery and reflects the simplicity of traditional rural food culture, representing purity and the timeless connection between food and heritage.",
    full:
    "Bhakka is a traditional and culturally significant dish of the Seemanchal region of Bihar, especially Kishanganj, as well as parts of eastern Nepal. It is a rice-based preparation made from coarsely ground rice flour, lightly seasoned, shaped by hand, and steamed until soft. This gentle cooking method preserves both the natural taste and nutritional value of rice. Historically, Bhakka developed in agrarian communities where rice was the primary staple crop. Steaming was one of the earliest and healthiest cooking techniques, requiring minimal resources. Because Bhakka does not need oil or heavy spices, it became a preferred daily food for farmers and working families. It was easy to prepare, filling, and suitable for all age groups. In Nepal and Seemanchal, Bhakka is often associated with traditional life and festive gatherings. It is commonly prepared in the early morning and served fresh, sometimes during festivals, family occasions, or as a special homemade breakfast. In many households, making Bhakka is a shared activity that brings family members together, strengthening cultural bonds. Bhakka is usually eaten with green chili chutney, coriander chutney, curd, or jaggery, depending on regional taste. Some variations include lightly sweetened Bhakka, while others keep it completely plain to highlight the natural flavor of rice. Despite regional differences, the soul of Bhakka remains the same—simple ingredients, slow cooking, and traditional wisdom. From a nutritional perspective, Bhakka is considered a wholesome and healthy food. Being steamed and made from whole grains, it is easy to digest, rich in carbohydrates for energy, and suitable for people seeking light and natural meals. Its low oil content makes it ideal for a balanced diet. Today, Bhakka continues to be an important symbol of traditional food heritage in Kishanganj and Nepal. It represents purity, simplicity, and the timeless connection between food, land, and culture. Even in modern times, Bhakka remains a cherished dish that carries the taste of tradition from one generation to the next.",
  },
  {
    id: 6,
    title: "Chana Chat",
    image: chana_chat,
    short:
    "Chana Chaat is a popular and healthy street food enjoyed in Kishanganj and across Bihar. Made with boiled chickpeas, onions, tomatoes, spices, and lemon juice, it is known for its tangy and spicy flavor. This refreshing snack has been a favorite among people of all ages for generations, representing the vibrant street food culture of the region. It is often eaten as an evening snack and is valued as a healthier alternative to fried foods, providing protein, fiber, and essential nutrients in a delicious and affordable package.",
    full:
    "Chana Chaat is a traditional and much-loved snack that holds a special place in the street food culture of Kishanganj and other parts of Bihar. Prepared using boiled chickpeas, fresh vegetables like onions and tomatoes, green chilies, coriander leaves, lemon juice, and aromatic spices, Chana Chaat offers a perfect balance of taste and nutrition. Historically, chickpeas have been a staple ingredient in Indian households for centuries due to their high nutritional value and affordability. Chana Chaat developed as a simple, filling, and quick-to-prepare dish that suited the busy lifestyle of market areas and street vendors. Over time, it became a favorite snack among students, workers, and travelers. In Kishanganj, Chana Chaat is commonly found at roadside stalls, local bazaars, near schools, and during fairs and festivals. Vendors often add their own regional touch by mixing tamarind chutney, green chutney, or special spice blends, making each serving unique in taste. Culturally, Chana Chaat represents everyday food that is light yet satisfying. It is widely preferred as a healthier alternative to fried snacks and is enjoyed throughout the year. Rich in protein, fiber, and essential nutrients, Chana Chaat supports digestion and provides lasting energy, which adds to its popularity. With its simplicity, affordability, and delicious flavor, Chana Chaat continues to be an integral part of Kishanganj’s local food tradition and India’s vibrant street food heritage.",
    },
  {
    id: 7,
    title: "Chana Muri",
    image: chana_muri,
    short:
    "Chana Muri is a popular crunchy snack from Bihar, made with puffed rice, roasted chickpeas, spices, and sometimes peanuts and chopped vegetables. It is light, flavorful, and perfect as a quick snack during evenings or for tea-time. This beloved street food combines locally available ingredients for a filling, inexpensive, and nutritious treat that has been enjoyed for generations. The balance of crunchiness, tang, spice, and freshness makes Chana Muri irresistible to locals and visitors, representing the vibrant snacking culture of Bihar.",
    full:
    "Chana Muri is a beloved street food and snack across Kishanganj and Bihar, famous for its crunchiness, tangy flavor, and ease of preparation. The dish primarily consists of puffed rice (muri) mixed with roasted chickpeas (chana), peanuts, chopped onions, tomatoes, green chilies, fresh coriander, and a tangy combination of lemon juice and spices like black salt, cumin powder, and red chili powder. The history of Chana Muri dates back to simple home snacks that combined locally available ingredients for a filling, inexpensive, and nutritious treat. Puffed rice, being lightweight and easily digestible, was commonly used in rural households, while roasted chickpeas added protein and substance, making it ideal for children and workers alike. In Kishanganj, Chana Muri is a staple in street food culture. Vendors often sell it in small paper packets near markets, schools, and bus stands. Many regional variations exist, with some adding grated coconut, tamarind chutney, or sev for extra texture and flavor. The balance of crunchiness, tang, spice, and freshness makes Chana Muri irresistible to locals and visitors. Culturally, Chana Muri represents quick, flavorful, and affordable snacking in Bihar. Its combination of protein, fiber, and energy-rich puffed rice makes it not only tasty but also a healthier alternative to deep-fried snacks. It is commonly enjoyed during festivals, evening tea-time, or even as a light breakfast option. With its vibrant flavors, easy preparation, and nutritional benefits, Chana Muri continues to hold a special place in Bihari culinary tradition and the hearts of snack lovers across the region.",
  },
  {
    id: 8,
    title: "Chandrakala",
    image: chandrakala,
    short:
    "Chandrakala is a traditional North Indian sweet, especially popular in Bihar, made from a thin, crispy maida (refined flour) shell filled with khoya (milk solids), sugar, cardamom, and chopped nuts like almonds and pistachios. Its crescent shape gives it the name 'Chandrakala,' meaning 'crescent moon,' symbolizing prosperity and joy in Indian culture. This delicate sweet has been prepared in households for generations, particularly during festivals like Diwali, Holi, and weddings. It is commonly prepared during festivals, weddings, and special occasions, representing celebration, hospitality, and the rich culinary heritage of Bihar.",
    full:
    "Chandrakala is a classic North Indian dessert with deep roots in Bihar’s festive cuisine, including districts like Kishanganj. The name “Chandrakala” literally means “crescent moon,” reflecting its iconic shape. This sweet consists of a thin, crisp outer shell made from refined flour (maida) enveloping a rich, aromatic filling of khoya (milk solids), sugar, cardamom, and chopped nuts such as almonds, cashews, and pistachios. Historically, Chandrakala has been prepared in Indian households for generations, particularly during festivals like Diwali, Holi, and weddings. Its delicate crescent shape symbolizes prosperity, joy, and completeness, making it a favored choice for gifting and festive celebrations. Over time, Chandrakala also became a popular item in sweet shops across Bihar and India, prized for its flaky texture and luxurious nutty filling. In Kishanganj, Chandrakala reflects both tradition and culinary creativity. While khoya-based fillings are most common, local variations sometimes include coconut or paneer, and sugar syrup is often flavored with saffron or rose water for extra aroma. Small bite-sized versions are frequently prepared for parties and weddings, demonstrating the sweet’s adaptability to different occasions. Culturally, Chandrakala represents celebration, hospitality, and indulgence. Though rich and sweet, it provides energy and nutrition from milk solids and nuts. Consumed in moderation, it is a source of protein, calcium, and healthy fats. Even today, despite the popularity of modern desserts, Chandrakala continues to hold a cherished place in Bihar’s culinary heritage, connecting people to their roots through its timeless taste, festive charm, and beautiful presentation.",
  },
  {
    id: 9,
    title: "Chicken Chawal",
    image: chicken_chawal,
    short:
    "Chicken Chawal is a popular and comforting dish widely enjoyed in Kishanganj and other parts of Bihar. It consists of flavorful, well-cooked rice served with spiced chicken curry, prepared using traditional Indian spices and slow-cooking techniques. Known for its rich taste and satisfying nature, this dish reflects the everyday food culture of the region where taste, nutrition, and simplicity come together perfectly. Chicken Chawal is commonly eaten as a wholesome meal during lunch or dinner, representing warmth, togetherness, and the hearty comfort food tradition of Bihar.",
    full:
    "Chicken Chawal is one of the most loved and widely consumed non-vegetarian dishes in Kishanganj, Bihar. It is a simple yet flavorful meal that combines aromatic rice with slow-cooked chicken curry prepared using traditional Indian spices. The dish reflects the everyday food culture of the region, where taste, nutrition, and simplicity come together in one plate. The preparation of Chicken Chawal involves marinating chicken with spices such as turmeric, red chili powder, coriander, ginger-garlic paste, and garam masala. The chicken is then cooked until tender, allowing the spices to blend deeply into the gravy. This richly spiced chicken curry is served alongside steamed or lightly flavored rice, creating a balanced and filling meal. Historically, Chicken Chawal gained popularity in Kishanganj due to its affordability, availability, and ease of preparation. It is commonly prepared in homes, small eateries, roadside food stalls, and local restaurants. The dish is especially popular during family gatherings, weekends, and casual celebrations. In many households, Chicken Chawal is also served during special occasions as a hearty alternative to vegetarian meals. Culturally, Chicken Chawal represents warmth, togetherness, and comfort. It is often enjoyed with side dishes such as salad, lemon wedges, green chutney, or curd, which enhance its flavor and freshness. Nutritionally, the dish provides a good balance of carbohydrates from rice and protein from chicken, making it an energy-rich and nourishing meal. Even today, Chicken Chawal remains a staple favorite in Kishanganj’s food culture. Its delicious taste, satisfying portion, and traditional cooking style make it a timeless dish that continues to be enjoyed by people of all ages.",
  },
  {
    id: 10,
    title: "Dahi Chuda",
    image: dahi_chuda,
    short:
    "Dahi Chuda is a traditional and nutritious dish widely enjoyed in Kishanganj and across Bihar. It is prepared using flattened rice (chuda) mixed with fresh curd and lightly seasoned with various ingredients like sugar, salt, or seasonal fruits. Known for its simplicity and refreshing taste, this dish has been a staple in rural and semi-urban households for generations. Dahi Chuda is commonly eaten as a healthy breakfast or light meal, especially during summer due to its cooling and digestive properties, representing the region's wisdom in creating wholesome, gentle foods.",
   full:
   "Dahi Chuda is a classic traditional dish that holds a special place in the food culture of Kishanganj and the wider Bihar region. It is made by soaking flattened rice (chuda) and mixing it with fresh curd, often enhanced with ingredients such as sugar or jaggery, salt, green chilies, mustard seeds, curry leaves, or seasonal fruits, depending on local preference. Historically, Dahi Chuda developed as a simple and nourishing meal suitable for daily consumption. Due to its minimal cooking process and easily available ingredients, it became especially popular in rural and semi-urban households. The dish is widely consumed during summer because of its cooling and digestive properties. In Kishanganj, Dahi Chuda is not only a regular household food but also an important part of festive and cultural traditions. It is commonly prepared during festivals, family gatherings, and religious occasions, where it is served as a light yet satisfying meal. The combination of curd and flattened rice provides essential nutrients, making it both healthy and filling. Culturally, Dahi Chuda represents simplicity, purity, and traditional wisdom in food habits. It reflects the region’s preference for wholesome meals that are easy to prepare and gentle on the stomach. Even today, despite the growing popularity of modern and fast foods, Dahi Chuda continues to be cherished for its traditional taste, health benefits, and cultural value. Dahi Chuda remains an important part of Bihar’s culinary heritage, symbolizing balance, nourishment, and the beauty of simple traditional food.",
  },
  {
    id: 12,
    title: "Fry Chida",
    image: fry_chida,
    short:
    "Fry Chida is a popular traditional snack enjoyed in Kishanganj and across Bihar. It is made by roasting flattened rice in oil or ghee with spices, peanuts, and sometimes vegetables, creating a delightful combination of flavors and textures. Known for its crispy texture and savory taste, this dish emerged as a practical and quick snack that could be prepared with minimal ingredients. Fry Chida is commonly eaten as a tea-time snack or light meal, representing the local preference for simple yet flavorful food that preserves traditional cooking methods while adapting to modern tastes.",
    full:
    "Fry Chida is a well-known traditional snack that forms an important part of the local food culture of Kishanganj and other regions of Bihar. It is prepared using flattened rice (chida), which is lightly fried or roasted in oil or ghee along with mustard seeds, curry leaves, peanuts, onions, green chilies, and mild spices. The preparation results in a crisp, aromatic, and flavorful dish. Historically, Fry Chida emerged as a practical and quick snack that could be prepared with minimal ingredients. Flattened rice has long been valued for its long shelf life and ease of use, making it a staple in many households. Fry Chida became especially popular as a convenient snack for travelers, farmers, and working families. In Kishanganj, Fry Chida is commonly served during festivals, family gatherings, and social occasions. It is also a preferred tea-time snack, often enjoyed with friends and guests. The dish reflects the local preference for simple yet flavorful food that can be prepared quickly without compromising taste. Culturally, Fry Chida symbolizes simplicity and everyday comfort food. Its crunchy texture and balanced spices make it suitable for people of all age groups. Even today, Fry Chida remains a favorite household snack, preserving traditional cooking methods while continuing to adapt to modern tastes. Fry Chida continues to be an important part of Bihar’s culinary heritage, representing the region’s love for light, crispy, and wholesome traditional snacks.",
  },
  {
    id: 13,
    title: "Handi Mutton",
    image: handi_mutton,
    short:
    "Handi Mutton is a traditional slow-cooked meat dish popular in Kishanganj and across Bihar. Prepared using tender mutton, aromatic spices, and cooked in a clay pot (handi), it is known for its rich flavor, thick gravy, and distinctive smoky aroma. This classic dish represents the region's rich culinary heritage, with slow cooking techniques that allow meat to cook gently in its own juices. Handi Mutton is commonly served during special occasions and family gatherings, symbolizing warmth, hospitality, and the celebration of traditional Indian cooking methods passed down through generations.",
    full:
    "Handi Mutton is a classic and flavorful meat dish that holds a special place in the traditional cuisine of Kishanganj and other parts of Bihar. The dish is named after the handi, a traditional earthen pot in which the mutton is slow-cooked. This method allows the meat to cook gently in its own juices, enhancing its tenderness and deepening the flavor of the spices. Historically, Handi Mutton has been associated with celebratory meals and special gatherings. Slow cooking in a clay pot was a common technique used in earlier times, as it preserved heat evenly and infused the food with an earthy aroma. The use of whole spices, onions, ginger, garlic, and traditional masalas reflects the rich culinary heritage of the region. In Kishanganj, Handi Mutton is often prepared during festivals, weddings, and large family occasions. It is usually served hot with rice, roti, or naan, making it a centerpiece dish of the meal. Local cooks take pride in preparing Handi Mutton using traditional methods to maintain its authentic taste. Culturally, Handi Mutton represents warmth, hospitality, and togetherness. The slow-cooking process symbolizes patience and care, values deeply rooted in traditional Indian cooking. Even today, despite modern cooking techniques, Handi Mutton continues to be cherished for its rich taste, aromatic gravy, and cultural significance. Handi Mutton remains an iconic dish of Bihar’s non-vegetarian cuisine, connecting generations through its traditional preparation, bold flavors, and festive appeal.",
  },
  {
    id: 14,
    title: "Jhalmuri",
    image: jhalmuri,
    short:
    "Jhalmuri is a popular Indian street snack made from puffed rice mixed with mustard oil, chopped onions, green chilies, spices, and fresh herbs. Known for its spicy and tangy taste, this traditional snack originated in Eastern India and reflects the vibrant street food culture of the region. The name comes from Bengali words 'jhal' meaning spicy and 'muri' meaning puffed rice, representing its distinctive flavor profile. Jhalmuri is widely enjoyed in Kishanganj and nearby regions as a light, flavorful snack that combines freshness, boldness, and the quick preparation style that makes it a beloved evening treat.",
    full:
    "Jhalmuri is a traditional and flavorful street food that originated in Eastern India and is widely popular in Kishanganj and surrounding areas. The snack is primarily made using puffed rice (muri), mixed with mustard oil, onions, green chilies, coriander leaves, lemon juice, and a blend of local spices. Its name comes from the Bengali words “jhal” meaning spicy and “muri” meaning puffed rice. Historically, Jhalmuri developed as an affordable and nutritious snack that could be prepared quickly using easily available ingredients. The use of mustard oil gives it a distinctive aroma and sharp flavor, setting it apart from other puffed rice snacks. Over time, Jhalmuri became a staple street food, especially in markets, railway stations, and evening food stalls. In Kishanganj, Jhalmuri is enjoyed by people of all age groups as an evening snack. It is often customized according to taste, with variations including roasted peanuts, boiled potatoes, cucumbers, tomatoes, or sev. Vendors prepare it fresh on the spot, ensuring a crunchy texture and bold flavor. Culturally, Jhalmuri represents the vibrant street food culture of Eastern India. It reflects simplicity, freshness, and local taste preferences. Light yet flavorful, it is commonly associated with casual gatherings, travel snacks, and everyday enjoyment. Jhalmuri continues to be loved for its crisp texture, spicy-tangy flavor, and quick preparation, making it an important part of regional snack culture and a favorite street food choice.",
  },
  {
    id: 15,
    title: "Khichdi",
    image: khichdi,
    short:
    "Khichdi is a simple and traditional Indian dish made from rice and lentils, cooked together with mild spices. Widely consumed in Kishanganj and across Bihar, Khichdi is valued for its comforting taste, easy digestion, and nourishing qualities. It is commonly eaten as a wholesome meal, especially during winters and on auspicious days. It is a wholesome meal. In Bihar, Khichdi is especially associated with the festival of Makar Sankranti, where it is prepared as a special celebratory dish and shared within families and communities.",
    full:
    "Khichdi is one of the oldest and most cherished dishes in Indian cuisine, holding deep cultural and dietary significance. Prepared by cooking rice and lentils together, Khichdi is known for its simplicity, balanced nutrition, and soothing flavor. In Kishanganj and other parts of Bihar, it is considered a staple comfort food enjoyed by people of all age groups. Historically, Khichdi has been mentioned in ancient Indian texts as a nourishing and easily digestible meal. Its minimal ingredients and gentle cooking process made it ideal for daily consumption, as well as for people recovering from illness. Over time, regional variations developed, using different types of lentils, vegetables, and spices. In Bihar, Khichdi is especially associated with the festival of Makar Sankranti, where it is prepared as a special celebratory dish and shared within families and communities. It is traditionally served hot with accompaniments such as ghee, pickle, curd, papad, and sometimes vegetables or chutney. Culturally, Khichdi symbolizes simplicity, warmth, and togetherness. It reflects the traditional Indian belief in food as nourishment for both the body and soul. Despite the rise of modern and elaborate dishes, Khichdi continues to remain a timeless favorite due to its comforting taste and health benefits. Khichdi stands as a symbol of Indian culinary heritage, representing balance, nourishment, and tradition through its humble yet satisfying preparation.",
  },
  {
    id: 16,
    title: "Machi Chawal",
    image: machi_chawal,
    short:
    "Machhi Chawal is a traditional meal consisting of fish curry served with steamed rice. Popular in Kishanganj and other parts of Bihar, the dish is known for its light yet flavorful taste and nutritional value. It is commonly enjoyed as a regular lunch or dinner meal, especially in areas close to rivers and water bodies.Machhi Chawal represents simplicity, freshness, and a close connection to nature. It reflects the traditional lifestyle of the region.",
    full:
    "Machhi Chawal is a classic and comforting dish that holds an important place in the food culture of Kishanganj and several regions of Bihar. The meal typically includes fresh fish cooked in a mildly spiced gravy, served with plain steamed rice. The simplicity of the dish highlights the natural flavor of the fish while maintaining a balanced and wholesome meal. Historically, fish has been a significant part of the diet in riverine regions of Bihar due to easy availability from local rivers and ponds. Traditional cooking methods use mustard oil, turmeric, onions, garlic, ginger, and locally blended spices, giving the fish curry its distinctive aroma and taste. The dish evolved as an everyday meal that was both nourishing and easy to prepare. In Kishanganj, Machhi Chawal is commonly prepared at home and is also served in local eateries. It is often enjoyed during lunch, accompanied by lemon, green chilies, or a simple salad. Different varieties of local fish are used depending on season and availability, adding variety to the dish. Culturally, Machhi Chawal represents simplicity, freshness, and a close connection to nature. It reflects the traditional lifestyle of the region, where food is prepared using locally sourced ingredients and traditional techniques. Even today, Machhi Chawal remains a beloved meal due to its light digestion, rich protein content, and authentic taste. Machhi Chawal continues to be an essential part of Bihar’s culinary heritage, offering a perfect balance of flavor, nutrition, and tradition.",
  },
  {
    id: 17,
    title: "Malpua",
    image: malpua,
    short:
    "Malpua is a traditional Indian sweet made from a batter of flour, milk, and sugar, deep-fried in ghee and soaked in sugar syrup. Popular in Kishanganj and across Bihar, Malpua is especially enjoyed during festivals and religious occasions for its soft texture and rich flavor. In Bihar, it is an important offering during Chhath Puja, where it is prepared as prasad and offered to the Sun God.",
    full:
    "Malpua is one of the oldest and most loved traditional sweets of India, holding special cultural importance in Bihar, including the region of Kishanganj. It is prepared by deep-frying a smooth batter made from flour, milk, and aromatic ingredients such as cardamom and fennel seeds, and then dipping it in sugar syrup. The result is a soft, juicy, and flavorful dessert with a golden surface. Historically, Malpua has been associated with religious rituals and festive celebrations. In Bihar, it is an important offering during Chhath Puja, where it is prepared as prasad and offered to the Sun God. Its preparation using ghee and milk reflects the traditional belief in purity and nourishment. In Kishanganj, Malpua is commonly made during festivals like Holi, Diwali, and family functions. It is often served warm and paired with curd, rabri, or plain milk, enhancing its taste and richness. Different regional variations exist, some using banana, coconut, or khoya to add unique flavors. Culturally, Malpua symbolizes devotion, celebration, and togetherness. The slow frying process and use of traditional ingredients represent care and tradition passed down through generations. Despite modern desserts becoming popular, Malpua continues to hold a special place in homes and sweet shops. Malpua remains a cherished part of Bihar’s sweet heritage, loved for its simplicity, rich taste, and deep cultural significance.",
  },
  {
    id: 18,
    title: "Rasgulla",
    image: rasgulla,
    short:
    "Rasgulla is a famous Indian sweet made from soft chhena (fresh cottage cheese) balls cooked in light sugar syrup. Loved in Kishanganj and across Bihar, Rasgulla is known for its spongy texture, mild sweetness, and refreshing taste. It is commonly served during festivals, celebrations, and special occasions. Historically, Rasgulla gained popularity due to its simple ingredients and light texture, making it suitable for all age groups.",
    full:
    "Rasgulla is one of the most popular and widely recognized sweets of the Indian subcontinent. Prepared from fresh chhena formed into small balls and cooked in sugar syrup, Rasgulla is admired for its soft, spongy texture and delicate sweetness. Although it originated in Eastern India, Rasgulla has become a beloved dessert across Bihar, including the region of Kishanganj. Historically, Rasgulla gained popularity due to its simple ingredients and light texture, making it suitable for all age groups. The technique of curdling milk to make chhena and cooking it in sugar syrup reflects traditional sweet-making practices that have been refined over generations. In Kishanganj, Rasgulla is commonly served during festivals, family functions, weddings, and religious ceremonies. It is often offered to guests as a symbol of happiness and celebration. Local sweet shops prepare Rasgulla fresh daily to maintain its softness and freshness. Culturally, Rasgulla represents joy, hospitality, and festivity. Its light and refreshing nature makes it a preferred dessert after heavy meals. Even today, Rasgulla continues to hold a special place in Indian celebrations due to its timeless appeal and comforting taste. Rasgulla remains an essential part of India’s sweet heritage, cherished for its simplicity, softness, and universal popularity.",
  },
  {
    id: 19,
    title: "Sattu Paratha",
    image: sattu_paratha,
    short:
    "Sattu Paratha is a traditional and nutritious Indian flatbread popular in Bihar and surrounding regions. Stuffed with roasted gram flour (sattu) mixed with spices, onions, and mustard oil, it is known for its rich flavor and high energy value. Sattu Paratha is commonly enjoyed as a wholesome breakfast or lunch. In regions like Kishanganj, Sattu Paratha is commonly served with curd, pickle, green chutney, or butter.",
    full:
    "Sattu Paratha is a classic dish from the eastern Indian states, especially Bihar, where it is valued for both its taste and nutritional benefits. The paratha is prepared by stuffing whole wheat dough with sattu, a flour made from roasted gram (chana), blended with onions, green chilies, herbs, spices, and mustard oil. It is then rolled and cooked on a hot griddle until golden and crisp. Historically, sattu has been considered a staple food for farmers and laborers due to its high protein content and ability to provide sustained energy. Sattu Paratha emerged as a complete meal that could be prepared easily and consumed during long working hours, especially in rural areas. In regions like Kishanganj, Sattu Paratha is commonly served with curd, pickle, green chutney, or butter. It is enjoyed throughout the year and is especially popular during summer, as sattu is known for its cooling properties. Culturally, Sattu Paratha represents simplicity, strength, and traditional wisdom in Indian cuisine. Its use of natural, minimally processed ingredients reflects a deep connection with local agriculture and healthy eating practices. Sattu Paratha continues to be a favorite dish in Bihar, appreciated for its authentic taste, nutritional richness, and role as a wholesome traditional meal.",
  },
{
    id: 20,
    title: "Sewai",
    image: sewai,
    short:
    "Sewai is a traditional Indian dish made from thin wheat flour noodles, commonly enjoyed in Bihar and neighboring regions. It is known for its simplicity, light texture, and versatility, and can be prepared as a savory meal or a mildly spiced snack. In many homes, Sewai is prepared during regular meals as well as on specific occasions.",
    full:
    "Sewai is a traditional food item prepared from wheat flour dough that is shaped into thin noodles and then cooked according to regional preferences. In Bihar, including areas like Kishanganj, Sewai is commonly prepared as a simple yet comforting dish, often served with vegetables, spices, or light gravy. Historically, Sewai has been a part of everyday home cooking due to its ease of preparation and use of basic ingredients. It was especially popular in households where homemade, freshly prepared meals were preferred over complex dishes. The dish reflects the traditional lifestyle where food was nutritious, filling, and economical. In many homes, Sewai is prepared during regular meals as well as on specific occasions. It can be lightly roasted or boiled and then cooked with onions, green chilies, mustard oil, and local spices, giving it a distinct regional flavor. Some variations also include vegetables to enhance taste and nutrition. Culturally, Sewai represents simplicity and comfort in traditional Indian cuisine. It is valued not for richness, but for its wholesome nature and adaptability. Even today, Sewai continues to be enjoyed as a homely and satisfying dish that connects people to traditional cooking practices. Sewai remains a quiet yet important part of regional food culture, appreciated for its light taste, easy digestibility, and traditional roots.",
  },
  {
    id: 21,
    title: "Sheer Khurma",
    image: sheer_khurma,
    short:
    "Sheer Khurma is a traditional festive dessert prepared with milk, vermicelli, dates, and dry fruits. It is especially associated with Eid celebrations and is enjoyed as a symbol of joy, togetherness, and hospitality. The dish is known for its rich taste, creamy texture, and aromatic flavors. Sheer Khurma has become popular beyond religious occasions and is now enjoyed at weddings, family gatherings, and special events. While variations exist—such as adding condensed milk or coconut milk—the traditional recipe remains timeless and deeply cherished.",
    full:
    "Sheer Khurma is a classic dessert with deep cultural and religious significance, widely prepared in Muslim households across South Asia, including India. The name “Sheer Khurma” comes from Persian words, where sheer means milk and khurma means dates, highlighting its two key ingredients. Traditionally, Sheer Khurma is prepared by slow-cooking vermicelli in milk along with dates, sugar, ghee, and a variety of dry fruits such as almonds, cashews, pistachios, and raisins. Cardamom and saffron are often added to enhance its aroma and flavor. The slow cooking process allows the ingredients to blend beautifully, creating a rich and creamy dessert. Sheer Khurma holds special importance during Eid-ul-Fitr, where it is served to family members and guests as the first dish of the day after prayers. It represents warmth, generosity, and celebration, and is considered a gesture of hospitality and goodwill. Over time, Sheer Khurma has become popular beyond religious occasions and is now enjoyed at weddings, family gatherings, and special events. While variations exist—such as adding condensed milk or coconut milk—the traditional recipe remains timeless and deeply cherished. Sheer Khurma is more than just a dessert it is a cultural tradition that reflects celebration, unity, and the richness of heritage through its flavors and preparation.",
  },
  {
    id: 22,
    title: "Aloo Bhujiya",
    image: aloobhujiya,
    short:
    "Aloo Bhujia is a popular Indian snack made from potatoes, gram flour, and mild spices. Known for its crispy texture and savory taste, it is widely enjoyed across Bihar and North India as a tea-time snack or a topping for chaat dishes. It is a popular dry potato dish enjoyed in Kishanganj and across Bihar. Made with finely sliced potatoes, spices, and mustard oil, it is known for its crispy texture and spicy flavor. This simple yet flavorful dish is commonly eaten with rice, roti, or as a side dish. It is quick to prepare. It is loved in daily meals.",
    full:
    "Aloo Bhujia is a traditional savory snack that holds an important place in Indian snack culture. It is prepared by combining boiled potatoes with gram flour (besan), spices, and a small amount of oil or ghee. The mixture is pressed through a sev maker and deep-fried until crisp, resulting in thin, crunchy strands. The origin of Aloo Bhujia is closely linked to regional snack-making traditions where locally available ingredients were used to create flavorful and long-lasting foods. Over time, it became especially popular in North India and Bihar, where it is commonly consumed as a standalone snack or used as a garnish in chaat, poha, and other street foods. In areas like Kishanganj, Aloo Bhujia is enjoyed in households as well as sold by local vendors and sweet shops. Its mild yet flavorful seasoning makes it suitable for people of all age groups. It is often served with tea or mixed with onions, green chilies, and lemon juice for a quick snack. Culturally, Aloo Bhujia represents the creativity of Indian snack traditions, where simple ingredients are transformed into something crunchy and delicious. Despite the availability of modern packaged snacks, Aloo Bhujia continues to remain a favorite due to its traditional taste and versatility. Aloo Bhujia is cherished not only for its flavor but also for its role as a comfort snack that connects people to local food traditions.",
  },
]

export default foodData;
