import chhath from "../../assets/chhath.jpeg";
import holi from "../../assets/holi.jpeg"
import diwali from "../../assets/Diwali.webp";
import durga from "../../assets/2025-Durga-Puja.jpg";
import mahashivrati from "../../assets/shiv ratari.jpeg";
import saraswati from "../../assets/saraswati.webp"
import RakshaBandhan from "../../assets/rakhi.jpeg"
const festivalData = [
  {
    id: 1,
    title: "Chhath Puja",
    image: chhath,
    short:
          "Chhath Puja is one of the most important and sacred festivals of Bihar, dedicated to the worship of the Sun God and Chhathi Maiya. Lorem ipsum dolor sit amet, consectetur adipiscing elit. This festival is mainly celebrated to thank the Sun God for sustaining life on earth and to seek blessings for health, prosperity, and happiness. Devotees observe strict rituals, including fasting, holy bathing, and offering prayers at riverbanks. Chhath Puja reflects deep faith, discipline, and the cultural heritage of Bihar.",
    full:
      "Chhath Puja is a sacred and ancient festival that holds immense cultural, spiritual, and social significance in Bihar. Lorem ipsum dolor sit amet, consectetur adipiscing elit. This festival is dedicated to the worship of the Sun God (Surya Dev) and Chhathi Maiya, who are believed to be the ultimate sources of energy, life, health, and prosperity. Chhath Puja is one of the very few Hindu festivals that focuses on the direct worship of natural elements, especially the Sun, highlighting the deep connection between human life and nature. The festival is observed with strict discipline, purity, and devotion over four days, namely Nahay Khay, Kharna, Sandhya Arghya, and Usha Arghya. On Nahay Khay, devotees take a holy bath and begin the rituals with pure vegetarian food. Kharna involves a day-long fast followed by a simple meal, after which devotees observe a rigorous 36-hour fast without food and water. This fast reflects strong willpower, self-control, and unwavering faith. During Sandhya Arghya and Usha Arghya, devotees stand in rivers, ponds, or ghats and offer prayers to the setting and rising sun. Traditional offerings such as fruits, thekua, sugarcane, coconut, and other natural items are presented with devotion. These rituals symbolize gratitude towards nature for sustaining life on earth. The sight of devotees offering prayers in water, holding bamboo baskets filled with offerings, creates a deeply spiritual and peaceful environment. Riversides, ponds, and ghats are beautifully decorated with diyas, lamps, flowers, and lights, transforming the surroundings into a serene and divine space. Families, neighbors, and communities come together to support the devotees, reflecting unity, cooperation, and social harmony. Chhath Puja is not limited to religious worship; it also promotes environmental awareness, cleanliness, discipline, and respect for nature. Chhath Puja symbolizes purity of mind and body, discipline, gratitude, and harmony with natural forces. It strengthens family bonds, preserves cultural traditions, and reflects the rich heritage of Bihar. Due to its strict rituals, deep faith, and spiritual depth, Chhath Puja is regarded as one of the most revered, disciplined, and meaningful festivals of Bihar and holds a special place in the hearts of millions of devotees.",
  },
  {
    id: 2,
    title: "Holi Celebration",
    image: holi,
    short:
          "Holi is one of the most famous and widely celebrated festivals of Bihar, known for its vibrant colors, joyful atmosphere, and cultural significance. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Holi, also known as the festival of colors, is celebrated to mark the arrival of spring and the victory of good over evil. This festival brings people together as they play with colors, sing traditional folk songs, and share happiness with family and friends. The celebration begins with Holika Dahan, symbolizing the burning of negativity and evil forces. Holi reflects unity, love, and harmony among communities and showcases the rich cultural traditions of Bihar." ,
    full:
    "Holi is one of the most vibrant, joyful, and culturally rich festivals of Bihar, celebrated with immense enthusiasm in both towns and villages. This colorful festival is deeply rooted in the traditions, history, and social life of the people. Known as the Festival of Colors, Holi marks the arrival of spring and symbolizes new beginnings, happiness, love, and harmony. It represents the victory of good over evil and reminds people of the importance of truth, devotion, and togetherness. The celebrations begin with Holika Dahan, which takes place on the night before Holi. Bonfires are lit to symbolize the burning of evil forces and negative energies. This ritual is associated with the legend of Prahlad and Holika, highlighting how devotion and righteousness always triumph over arrogance and cruelty. People gather around the fire, offer prayers, and wish for peace, prosperity, and positivity in their lives. On the day of Holi, the atmosphere becomes lively and colorful. People of all ages come out of their homes to play with gulal, water colors, and balloons. Streets echo with laughter, folk songs, and traditional music, creating a festive environment filled with joy. Friends, families, and neighbors apply colors to each other, exchange warm greetings, and celebrate without any barriers of caste, age, or status. Old misunderstandings are forgotten, and relationships are renewed with love and forgiveness. Food plays a very important role in Holi celebrations in Bihar. Traditional dishes such as gujiya, dahi bada, malpua, puri, kheer, and various sweets are prepared with great care and shared with relatives and neighbors. These delicious foods add warmth and sweetness to the festival, making it even more special. Holi in Bihar is not just about colors; it is a cultural celebration that reflects unity, social bonding, and the true spirit of joy. It brings people together, strengthens relationships, and spreads happiness everywhere. The festival beautifully showcases Bihar’s rich heritage, communal harmony, and the timeless message of love, equality, and togetherness.",
  },
   {
    id: 2,
    title: "Diwali Festival",
    image: diwali,
    short:
         "Diwali is one of the most popular and widely celebrated festivals of Bihar, known as the festival of lights. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Diwali symbolizes the victory of light over darkness and good over evil. People decorate their homes with diyas, candles, and colorful rangoli, and worship Goddess Lakshmi for wealth and prosperity. The festival brings joy, hope, and togetherness among families and communities.",
        full:
        "Diwali is one of the most joyful, sacred, and widely celebrated festivals in Bihar, observed with deep devotion, excitement, and cultural pride. Also known as Deepavali, meaning “a row of lamps,” this festival symbolizes the victory of light over darkness, good over evil, and knowledge over ignorance. Diwali holds great religious and cultural importance and is celebrated by people of all ages across towns, villages, and cities in Bihar. The festival commemorates the return of Lord Rama to Ayodhya after his fourteen-year exile and his victory over the demon king Ravana. To welcome Lord Rama, Goddess Sita, and Lord Lakshman, the people of Ayodhya lit rows of diyas, a tradition that continues to this day. This story reminds people that truth, righteousness, and devotion always triumph over evil forces. Days before Diwali, people begin cleaning and decorating their homes, shops, and surroundings. Houses, temples, and streets are beautifully illuminated with earthen lamps (diyas), candles, lanterns, and colorful decorative lights, creating a magical and festive atmosphere. Rangoli designs made with colored powders, flowers, and rice are drawn at entrances to welcome positivity and prosperity. A significant ritual of Diwali is Lakshmi Puja, performed in homes and temples to seek the blessings of Goddess Lakshmi, the goddess of wealth and prosperity, and Lord Ganesha, the remover of obstacles. Families gather to offer prayers, light lamps, and chant mantras, hoping for success, peace, and happiness in their lives. Sharing sweets and gifts is an essential part of Diwali celebrations in Bihar. Traditional delicacies such as laddu, barfi, peda, kheer, thekua, and various homemade snacks are prepared and exchanged with relatives, neighbors, and friends. These sweet treats strengthen relationships and spread joy and warmth among people. Diwali in Bihar is not just a festival of lights; it is a celebration of hope, positivity, unity, and cultural values passed down through generations. The festival brings families together, encourages generosity and kindness, and fills hearts with happiness and gratitude. Through its rituals, lights, and traditions, Diwali beautifully reflects the rich cultural heritage and spiritual spirit of Bihar.",
  },
   {
    id: 2,
    title: "Durga Puja",
    image: durga,
    short:
    "Durga Puja is one of the most important and widely celebrated festivals of Bihar, dedicated to Goddess Durga. Lorem ipsum dolor sit amet, consectetur adipiscing elit. This festival symbolizes the victory of good over evil and celebrates the power of divine feminine energy. During Durga Puja, beautifully crafted idols of Goddess Durga are worshipped, and people gather in pandals to offer prayers and seek blessings. The festival reflects devotion, cultural richness, and togetherness.",
    full:
    "Durga Puja is one of the most grand, powerful, and spiritually significant festivals celebrated across Bihar with deep devotion, joy, and cultural enthusiasm. This sacred festival honors Goddess Durga, the symbol of strength, courage, and divine feminine power. Durga Puja commemorates the victory of Goddess Durga over the demon Mahishasura, representing the eternal triumph of good over evil and the victory of righteousness over injustice and darkness. During this festival, towns and cities across Bihar come alive with beautifully decorated pandals, each showcasing unique artistic themes, traditional craftsmanship, and creative idol designs. Skilled artisans create magnificent idols of Goddess Durga along with her children—Lord Ganesha, Goddess Lakshmi, Goddess Saraswati, and Lord Kartikeya. These idols are adorned with colorful clothes, jewelry, and intricate decorations, attracting devotees and visitors from far and wide. The celebrations extend over several days, starting from Shashthi and continuing till Vijayadashami (Dussehra). Devotees participate in various rituals, offer flowers, fruits, sweets, and light lamps while chanting prayers and mantras. The sound of drums, bells, and devotional songs fills the air, creating a powerful and divine atmosphere. People visit pandals, seek blessings, and immerse themselves in the spiritual energy of the festival. Cultural programs are an important part of Durga Puja in Bihar. Traditional music, folk dances, devotional performances, and dramas are organized, reflecting the rich cultural heritage of the region. Families, friends, and neighbors come together to celebrate, enjoy festive meals, and spend quality time with one another. Special dishes and sweets are prepared at home and shared, adding warmth and joy to the occasion. On Vijayadashami, the idols of Goddess Durga are immersed in rivers or water bodies, symbolizing her return to the divine realm. This emotional ritual represents hope, renewal, and the belief that Goddess Durga will return again the next year to bless her devotees. Durga Puja in Bihar is not only a religious event but also a vibrant cultural celebration that strengthens faith, unity, and social harmony. It reflects the deep-rooted traditions, artistic excellence, and spiritual spirit of Bihar, making it a festival of devotion, celebration, and togetherness.",
  },
   {
    id: 2,
    title: "Mahashivratri",
    image: mahashivrati,
    short:
    "Mahashivratri is one of the most sacred and widely observed festivals of Bihar, dedicated to the worship of Lord Shiva. Lorem ipsum dolor sit amet, consectetur adipiscing elit. This festival symbolizes devotion, spiritual awakening, and inner strength. Devotees observe fasting, visit Shiva temples, and offer milk, water, and bel leaves to the Shivling. Mahashivratri holds deep religious significance as it represents the union of divine energy and consciousness. The celebration reflects faith, discipline, and the rich spiritual traditions of Bihar.",
    full:
    "Mahashivratri is one of the most sacred and spiritually significant Hindu festivals, celebrated across Bihar with deep devotion, faith, and inner discipline. This powerful festival is dedicated to Lord Shiva, who is worshipped as the supreme divine force responsible for creation, preservation, and destruction of the universe. Mahashivratri holds a special place in Hindu tradition as a night of spiritual awakening, self-reflection, and divine connection. According to ancient beliefs and scriptures, Mahashivratri marks the night when Lord Shiva performed the cosmic dance (Tandava), symbolizing the continuous cycle of creation and destruction. It is also believed to be the auspicious night when Lord Shiva and Goddess Parvati were united in divine marriage. Because of these sacred associations, Mahashivratri is considered an extremely powerful occasion for spiritual growth, meditation, and liberation from ignorance. On this holy day, devotees observe strict fasting, practice self-control, and dedicate themselves to prayers and meditation. Many devotees remain awake throughout the night, chanting sacred mantras like “Om Namah Shivaya”, singing devotional bhajans, and reading religious texts. Temples across Bihar are beautifully decorated with flowers, lights, and incense, creating a calm and spiritually uplifting atmosphere. A central ritual of Mahashivratri is the Abhishek of the Shivling, where devotees offer milk, water, honey, curd, ghee, and sacred bel leaves to Lord Shiva. These offerings symbolize purity, devotion, and surrender to the divine. Devotees pray for peace, prosperity, good health, inner strength, and freedom from negative energies. Many believe that sincere worship on Mahashivratri helps remove ignorance, fear, and suffering from life and brings spiritual clarity. Large numbers of devotees visit famous Shiva temples, stand in long queues, and participate in special night-long pujas and rituals. The collective devotion and chanting create a powerful spiritual energy that inspires faith and inner peace among worshippers. Mahashivratri in Bihar is not just a religious festival but a profound spiritual celebration that encourages self-discipline, devotion, mindfulness, and harmony with the universe. It reminds people of the importance of inner purity, balance, and the eternal presence of divine consciousness in everyday life.",
  },
  {
    id: 2,
    title:"Saraswati Puja",
    image: saraswati,
    short:
    "Saraswati Puja is one of the most important and widely celebrated festivals of Bihar, especially related to education, knowledge, and wisdom. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Saraswati Puja is dedicated to Goddess Saraswati, who is worshipped as the goddess of learning, arts, music, and creativity. This festival is mainly celebrated by students, teachers, and educational institutions with great devotion. People offer books, pens, musical instruments, and flowers to the goddess, seeking blessings for success in education and intellectual growth. The festival reflects respect for knowledge, discipline, and cultural traditions of Bihar.",
    full:
    "Saraswati Puja is a highly significant and meaningful religious as well as cultural festival celebrated across Bihar with deep faith, devotion, and enthusiasm. This auspicious festival is dedicated to Goddess Saraswati, the divine embodiment of knowledge, wisdom, learning, music, art, and creativity. She is worshipped as the source of enlightenment who removes ignorance, confusion, and darkness from human life and guides people towards truth and understanding. It is strongly believed that worshipping Goddess Saraswati brings clarity of thought, intelligence, discipline, and success in education. For students, teachers, artists, and scholars, Saraswati Puja holds special importance. The festival inspires respect for learning and encourages intellectual and creative growth in society. During Saraswati Puja, schools, colleges, coaching centers, libraries, and homes across Bihar are beautifully decorated with flowers, lights, and colorful cloth. Idols of Goddess Saraswati, seated on a lotus and holding a veena, book, and rosary, are installed with great devotion. Devotees wear traditional and elegant attire, often in white or light-colored clothes, symbolizing purity and peace. Special prayers and rituals are performed, and devotees gather to chant hymns and mantras seeking the blessings of the goddess. Books, notebooks, pens, pencils, musical instruments, and art tools are placed near the idol, highlighting the importance of education, creativity, and culture in human life. On this day, students avoid reading or writing, showing respect to knowledge by offering their study materials to the goddess. Cultural programs such as devotional songs, classical music, poetry recitation, and educational activities are organized, especially in educational institutions. Community gatherings create an atmosphere of unity, learning, and positivity. The festival also promotes discipline, humility, and gratitude towards teachers and mentors. Saraswati Puja in Bihar is not just a religious celebration but a beautiful tribute to education, wisdom, art, and intellectual development. It reminds society of the power of knowledge and the role of learning in shaping a better and enlightened future.",
  },
    {
    id: 2,
    title:"Raksha Bandhan",
    image: RakshaBandhan,
    short:
    "Raksha Bandhan Bharat ka ek prachin tyohar hai jo suraksha aur prem ke pavitra bandhan ko darshata hai. Is tyohar ka sambandh pauranik kathao, Mahabharat aur aitihasik ghatnaon se juda hua hai, jo bhai–behen ke atoot rishte ko majboot banata hai.",
    full:
    "Raksha Bandhan Bharat ka ek bahut hi prachin aur pavitra tyohar hai, jiska itihaas hazaron saal purana mana jata hai. “Raksha” ka arth hai suraksha aur “Bandhan” ka matlab hai rishta, is prakar yeh tyohar suraksha ke pavitra bandhan ka pratik hai. Prarambhik samay me raksha sutra sirf bhai–behen ke beech nahi, balki raja, yoddha aur pujariyon dwara bhi baandha jata tha. Pauranik kathao ke anusaar, Indra aur asuron ke yudh ke dauran Indrani ne Indra ki kalai par raksha sutra baandha tha, jisse unhe vijay prapt hui. Mahabharat me Draupadi aur Shree Krishna ki katha Raksha Bandhan ke prem aur samarpan ko darshati hai. Itihas me Rani Karnavati aur Mughal Badshah Humayun ki kahani is tyohar ko manavta aur samman ka pratik banati hai. Samay ke saath Raksha Bandhan ka swaroop aur bhi vistarit hota gaya. Aaj yeh tyohar parivaarik ekta, naari samman, prem aur zimmedari ka sandesh deta hai. Raksha Bandhan bharatiya sanskriti ki gahrai aur rishton ki pavitrata ko sundar roop se prastut karta hai.",
  },
  

    ];

export default festivalData;
