import madhubani from "../../assets/culturePage/madhubani.png";

const festivalData = [
  {
    id: 1,
    title: "Madhubani Painting",
    image: madhubani,
    short:
      "Madhubani painting is one of the most famous art forms of Bihar, known for its vibrant colors and mythological themes. lorem ipsum dolor sit amet, consectetur adipiscing elit. Madhubani painting, also known as Mithila art, is a traditional Indian folk art that originates from the Mithila region of Bihar. This art form is characterized by intricate patterns, vibrant colors, and elaborate motifs, often depicting nature, mythology, and cultural traditions. Artists traditionally use natural dyes and pigments derived from plants, flowers, and minerals, and paint on walls, cloth, or handmade paper." ,
    full:
      "Madhubani painting, also known as Mithila art, originated in the Mithila region of Bihar. Traditionally created by women on mud walls, floors, and cloth, this art form depicts scenes from Hindu mythology, nature, and daily life. Natural dyes and pigments are used, making it eco-friendly. Today, Madhubani art has gained international recognition and is practiced on canvas, paper, and fabric.Common themes include scenes from Hindu epics like the Ramayana and Mahabharata, as well as representations of animals, birds, flowers, and daily village life. Madhubani painting is unique for its use of bold lines, geometric patterns, and bright, contrasting colors. Historically, it was practiced mainly by women during festivals, weddings, and religious rituals, making it not only an art form but also a reflection of social and cultural life in Mithila. Today, Madhubani art is recognized globally and has become a symbol of India’s rich folk heritage.Common themes include scenes from Hindu epics like the Ramayana and Mahabharata, as well as representations of animals, birds, flowers, and daily village life. Madhubani painting is unique for its use of bold lines, geometric patterns, and bright, contrasting colors. Historically, it was practiced mainly by women during festivals, weddings, and religious rituals, making it not only an art form but also a reflection of social and cultural life in Mithila. Today, Madhubani art is recognized globally and has become a symbol of India’s rich folk heritage."
  },
  {
    id: 2,
    title: "Sikki Grass Craft",
    image: madhubani,
    short:
      "Madhubani painting is one of the most famous art forms of Bihar, known for its vibrant colors and mythological themes. lorem ipsum dolor sit amet, consectetur adipiscing elit. Madhubani painting, also known as Mithila art, is a traditional Indian folk art that originates from the Mithila region of Bihar. This art form is characterized by intricate patterns, vibrant colors, and elaborate motifs, often depicting nature, mythology, and cultural traditions. Artists traditionally use natural dyes and pigments derived from plants, flowers, and minerals, and paint on walls, cloth, or handmade paper." ,
    full:
      "Madhubani painting, also known as Mithila art, originated in the Mithila region of Bihar. Traditionally created by women on mud walls, floors, and cloth, this art form depicts scenes from Hindu mythology, nature, and daily life. Natural dyes and pigments are used, making it eco-friendly. Today, Madhubani art has gained international recognition and is practiced on canvas, paper, and fabric.Common themes include scenes from Hindu epics like the Ramayana and Mahabharata, as well as representations of animals, birds, flowers, and daily village life. Madhubani painting is unique for its use of bold lines, geometric patterns, and bright, contrasting colors. Historically, it was practiced mainly by women during festivals, weddings, and religious rituals, making it not only an art form but also a reflection of social and cultural life in Mithila. Today, Madhubani art is recognized globally and has become a symbol of India’s rich folk heritage.Common themes include scenes from Hindu epics like the Ramayana and Mahabharata, as well as representations of animals, birds, flowers, and daily village life. Madhubani painting is unique for its use of bold lines, geometric patterns, and bright, contrasting colors. Historically, it was practiced mainly by women during festivals, weddings, and religious rituals, making it not only an art form but also a reflection of social and cultural life in Mithila. Today, Madhubani art is recognized globally and has become a symbol of India’s rich folk heritage."
  },
   {
    id: 2,
    title: "Sikki Grass Craft",
    image: madhubani,
    short:
      "Madhubani painting is one of the most famous art forms of Bihar, known for its vibrant colors and mythological themes. lorem ipsum dolor sit amet, consectetur adipiscing elit. Madhubani painting, also known as Mithila art, is a traditional Indian folk art that originates from the Mithila region of Bihar. This art form is characterized by intricate patterns, vibrant colors, and elaborate motifs, often depicting nature, mythology, and cultural traditions. Artists traditionally use natural dyes and pigments derived from plants, flowers, and minerals, and paint on walls, cloth, or handmade paper." ,
    full:
      "Madhubani painting, also known as Mithila art, originated in the Mithila region of Bihar. Traditionally created by women on mud walls, floors, and cloth, this art form depicts scenes from Hindu mythology, nature, and daily life. Natural dyes and pigments are used, making it eco-friendly. Today, Madhubani art has gained international recognition and is practiced on canvas, paper, and fabric.Common themes include scenes from Hindu epics like the Ramayana and Mahabharata, as well as representations of animals, birds, flowers, and daily village life. Madhubani painting is unique for its use of bold lines, geometric patterns, and bright, contrasting colors. Historically, it was practiced mainly by women during festivals, weddings, and religious rituals, making it not only an art form but also a reflection of social and cultural life in Mithila. Today, Madhubani art is recognized globally and has become a symbol of India’s rich folk heritage.Common themes include scenes from Hindu epics like the Ramayana and Mahabharata, as well as representations of animals, birds, flowers, and daily village life. Madhubani painting is unique for its use of bold lines, geometric patterns, and bright, contrasting colors. Historically, it was practiced mainly by women during festivals, weddings, and religious rituals, making it not only an art form but also a reflection of social and cultural life in Mithila. Today, Madhubani art is recognized globally and has become a symbol of India’s rich folk heritage."
  },
   {
    id: 2,
    title: "Sikki Grass Craft",
    image: madhubani,
    short:
      "Madhubani painting is one of the most famous art forms of Bihar, known for its vibrant colors and mythological themes. lorem ipsum dolor sit amet, consectetur adipiscing elit. Madhubani painting, also known as Mithila art, is a traditional Indian folk art that originates from the Mithila region of Bihar. This art form is characterized by intricate patterns, vibrant colors, and elaborate motifs, often depicting nature, mythology, and cultural traditions. Artists traditionally use natural dyes and pigments derived from plants, flowers, and minerals, and paint on walls, cloth, or handmade paper." ,
    full:
      "Madhubani painting, also known as Mithila art, originated in the Mithila region of Bihar. Traditionally created by women on mud walls, floors, and cloth, this art form depicts scenes from Hindu mythology, nature, and daily life. Natural dyes and pigments are used, making it eco-friendly. Today, Madhubani art has gained international recognition and is practiced on canvas, paper, and fabric.Common themes include scenes from Hindu epics like the Ramayana and Mahabharata, as well as representations of animals, birds, flowers, and daily village life. Madhubani painting is unique for its use of bold lines, geometric patterns, and bright, contrasting colors. Historically, it was practiced mainly by women during festivals, weddings, and religious rituals, making it not only an art form but also a reflection of social and cultural life in Mithila. Today, Madhubani art is recognized globally and has become a symbol of India’s rich folk heritage.Common themes include scenes from Hindu epics like the Ramayana and Mahabharata, as well as representations of animals, birds, flowers, and daily village life. Madhubani painting is unique for its use of bold lines, geometric patterns, and bright, contrasting colors. Historically, it was practiced mainly by women during festivals, weddings, and religious rituals, making it not only an art form but also a reflection of social and cultural life in Mithila. Today, Madhubani art is recognized globally and has become a symbol of India’s rich folk heritage."
  },
   {
    id: 2,
    title: "Sikki Grass Craft",
    image: madhubani,
    short:
      "Madhubani painting is one of the most famous art forms of Bihar, known for its vibrant colors and mythological themes. lorem ipsum dolor sit amet, consectetur adipiscing elit. Madhubani painting, also known as Mithila art, is a traditional Indian folk art that originates from the Mithila region of Bihar. This art form is characterized by intricate patterns, vibrant colors, and elaborate motifs, often depicting nature, mythology, and cultural traditions. Artists traditionally use natural dyes and pigments derived from plants, flowers, and minerals, and paint on walls, cloth, or handmade paper." ,
    full:
      "Madhubani painting, also known as Mithila art, originated in the Mithila region of Bihar. Traditionally created by women on mud walls, floors, and cloth, this art form depicts scenes from Hindu mythology, nature, and daily life. Natural dyes and pigments are used, making it eco-friendly. Today, Madhubani art has gained international recognition and is practiced on canvas, paper, and fabric.Common themes include scenes from Hindu epics like the Ramayana and Mahabharata, as well as representations of animals, birds, flowers, and daily village life. Madhubani painting is unique for its use of bold lines, geometric patterns, and bright, contrasting colors. Historically, it was practiced mainly by women during festivals, weddings, and religious rituals, making it not only an art form but also a reflection of social and cultural life in Mithila. Today, Madhubani art is recognized globally and has become a symbol of India’s rich folk heritage.Common themes include scenes from Hindu epics like the Ramayana and Mahabharata, as well as representations of animals, birds, flowers, and daily village life. Madhubani painting is unique for its use of bold lines, geometric patterns, and bright, contrasting colors. Historically, it was practiced mainly by women during festivals, weddings, and religious rituals, making it not only an art form but also a reflection of social and cultural life in Mithila. Today, Madhubani art is recognized globally and has become a symbol of India’s rich folk heritage."
  }
    ];

export default festivalData;
