import thekua from "../../assets/thekua.png";
import aloobhujiya from "/src/assets/aloo_bhujiya.png";
import baiganbhaja from "/src/assets/baigan_bhaja.png";
import balushai from "/src/assets/balushai.png";
import bhakka from "/src/assets/bhakka.png";
import chana_chat from "/src/assets/chana_chat.png";
import chana_muri from "/src/assets/chana_muri.png";
import chandrakala from "/src/assets/chandrakala.png";
import chicken_chawal from "/src/assets/chicken_chawal.png";
import dahi_chuda from "/src/assets/dahi_chuda.png";
import daal_puri from "/src/assets/daal_puri3.png";
import fry_chida from "/src/assets/fry_chida.png";
import handi_mutton from "/src/assets/handi_mutton.png";
import jhalmuri from "/src/assets/jhalmuri.png";
import khichdi from "/src/assets/khichdi.png";
import machi_chawal from "/src/assets/machi_chawal.png";
import malpua from "/src/assets/malpua.png";
import rasgulla from "/src/assets/rasgulla.png";
import sattu_paratha from "/src/assets/sattu_paratha.png";
import sewai from "/src/assets/sewai.png";
import sheer_khurma from "/src/assets/sheer_khurma.png";
import litti_chokha from "/src/assets/litti.jpg";
// import sattu_paratha from "/src/assets/sattu_paratha.png";


const foodData = [
  {
    id: 1,
    title: "Madhubani Painting",
    image: litti_chokha,
    short:
      "Madhubani painting is one of the most famous art forms of Bihar, known for its vibrant colors and mythological themes. lorem ipsum dolor sit amet, consectetur adipiscing elit. Madhubani painting, also known as Mithila art, is a traditional Indian folk art that originates from the Mithila region of Bihar. This art form is characterized by intricate patterns, vibrant colors, and elaborate motifs, often depicting nature, mythology, and cultural traditions. Artists traditionally use natural dyes and pigments derived from plants, flowers, and minerals, and paint on walls, cloth, or handmade paper." ,
    full:
      "Madhubani painting, also known as Mithila art, originated in the Mithila region of Bihar. Traditionally created by women on mud walls, floors, and cloth, this art form depicts scenes from Hindu mythology, nature, and daily life. Natural dyes and pigments are used, making it eco-friendly. Today, Madhubani art has gained international recognition and is practiced on canvas, paper, and fabric.Common themes include scenes from Hindu epics like the Ramayana and Mahabharata, as well as representations of animals, birds, flowers, and daily village life. Madhubani painting is unique for its use of bold lines, geometric patterns, and bright, contrasting colors. Historically, it was practiced mainly by women during festivals, weddings, and religious rituals, making it not only an art form but also a reflection of social and cultural life in Mithila. Today, Madhubani art is recognized globally and has become a symbol of India’s rich folk heritage.Common themes include scenes from Hindu epics like the Ramayana and Mahabharata, as well as representations of animals, birds, flowers, and daily village life. Madhubani painting is unique for its use of bold lines, geometric patterns, and bright, contrasting colors. Historically, it was practiced mainly by women during festivals, weddings, and religious rituals, making it not only an art form but also a reflection of social and cultural life in Mithila. Today, Madhubani art is recognized globally and has become a symbol of India’s rich folk heritage."
  },
  {
    id: 2,
    title: "Sikki Grass Craft",
    image: thekua,
    short:
      "Madhubani painting is one of the most famous art forms of Bihar, known for its vibrant colors and mythological themes. lorem ipsum dolor sit amet, consectetur adipiscing elit. Madhubani painting, also known as Mithila art, is a traditional Indian folk art that originates from the Mithila region of Bihar. This art form is characterized by intricate patterns, vibrant colors, and elaborate motifs, often depicting nature, mythology, and cultural traditions. Artists traditionally use natural dyes and pigments derived from plants, flowers, and minerals, and paint on walls, cloth, or handmade paper." ,
    full:
      "Madhubani painting, also known as Mithila art, originated in the Mithila region of Bihar. Traditionally created by women on mud walls, floors, and cloth, this art form depicts scenes from Hindu mythology, nature, and daily life. Natural dyes and pigments are used, making it eco-friendly. Today, Madhubani art has gained international recognition and is practiced on canvas, paper, and fabric.Common themes include scenes from Hindu epics like the Ramayana and Mahabharata, as well as representations of animals, birds, flowers, and daily village life. Madhubani painting is unique for its use of bold lines, geometric patterns, and bright, contrasting colors. Historically, it was practiced mainly by women during festivals, weddings, and religious rituals, making it not only an art form but also a reflection of social and cultural life in Mithila. Today, Madhubani art is recognized globally and has become a symbol of India’s rich folk heritage.Common themes include scenes from Hindu epics like the Ramayana and Mahabharata, as well as representations of animals, birds, flowers, and daily village life. Madhubani painting is unique for its use of bold lines, geometric patterns, and bright, contrasting colors. Historically, it was practiced mainly by women during festivals, weddings, and religious rituals, making it not only an art form but also a reflection of social and cultural life in Mithila. Today, Madhubani art is recognized globally and has become a symbol of India’s rich folk heritage."
  },
   {
    id: 2,
    title: "Sikki Grass Craft",
    image: baiganbhaja,
    short:
      "Madhubani painting is one of the most famous art forms of Bihar, known for its vibrant colors and mythological themes. lorem ipsum dolor sit amet, consectetur adipiscing elit. Madhubani painting, also known as Mithila art, is a traditional Indian folk art that originates from the Mithila region of Bihar. This art form is characterized by intricate patterns, vibrant colors, and elaborate motifs, often depicting nature, mythology, and cultural traditions. Artists traditionally use natural dyes and pigments derived from plants, flowers, and minerals, and paint on walls, cloth, or handmade paper." ,
    full:
      "Madhubani painting, also known as Mithila art, originated in the Mithila region of Bihar. Traditionally created by women on mud walls, floors, and cloth, this art form depicts scenes from Hindu mythology, nature, and daily life. Natural dyes and pigments are used, making it eco-friendly. Today, Madhubani art has gained international recognition and is practiced on canvas, paper, and fabric.Common themes include scenes from Hindu epics like the Ramayana and Mahabharata, as well as representations of animals, birds, flowers, and daily village life. Madhubani painting is unique for its use of bold lines, geometric patterns, and bright, contrasting colors. Historically, it was practiced mainly by women during festivals, weddings, and religious rituals, making it not only an art form but also a reflection of social and cultural life in Mithila. Today, Madhubani art is recognized globally and has become a symbol of India’s rich folk heritage.Common themes include scenes from Hindu epics like the Ramayana and Mahabharata, as well as representations of animals, birds, flowers, and daily village life. Madhubani painting is unique for its use of bold lines, geometric patterns, and bright, contrasting colors. Historically, it was practiced mainly by women during festivals, weddings, and religious rituals, making it not only an art form but also a reflection of social and cultural life in Mithila. Today, Madhubani art is recognized globally and has become a symbol of India’s rich folk heritage."
  },
   {
    id: 3,
    title: "Sikki Grass Craft",
    image: balushai,
    short:
      "Madhubani painting is one of the most famous art forms of Bihar, known for its vibrant colors and mythological themes. lorem ipsum dolor sit amet, consectetur adipiscing elit. Madhubani painting, also known as Mithila art, is a traditional Indian folk art that originates from the Mithila region of Bihar. This art form is characterized by intricate patterns, vibrant colors, and elaborate motifs, often depicting nature, mythology, and cultural traditions. Artists traditionally use natural dyes and pigments derived from plants, flowers, and minerals, and paint on walls, cloth, or handmade paper." ,
    full:
      "Madhubani painting, also known as Mithila art, originated in the Mithila region of Bihar. Traditionally created by women on mud walls, floors, and cloth, this art form depicts scenes from Hindu mythology, nature, and daily life. Natural dyes and pigments are used, making it eco-friendly. Today, Madhubani art has gained international recognition and is practiced on canvas, paper, and fabric.Common themes include scenes from Hindu epics like the Ramayana and Mahabharata, as well as representations of animals, birds, flowers, and daily village life. Madhubani painting is unique for its use of bold lines, geometric patterns, and bright, contrasting colors. Historically, it was practiced mainly by women during festivals, weddings, and religious rituals, making it not only an art form but also a reflection of social and cultural life in Mithila. Today, Madhubani art is recognized globally and has become a symbol of India’s rich folk heritage.Common themes include scenes from Hindu epics like the Ramayana and Mahabharata, as well as representations of animals, birds, flowers, and daily village life. Madhubani painting is unique for its use of bold lines, geometric patterns, and bright, contrasting colors. Historically, it was practiced mainly by women during festivals, weddings, and religious rituals, making it not only an art form but also a reflection of social and cultural life in Mithila. Today, Madhubani art is recognized globally and has become a symbol of India’s rich folk heritage."
  },
   {
    id: 4,
    title: "Sikki Grass Craft",
    image: bhakka,
    short:
      "Madhubani painting is one of the most famous art forms of Bihar, known for its vibrant colors and mythological themes. lorem ipsum dolor sit amet, consectetur adipiscing elit. Madhubani painting, also known as Mithila art, is a traditional Indian folk art that originates from the Mithila region of Bihar. This art form is characterized by intricate patterns, vibrant colors, and elaborate motifs, often depicting nature, mythology, and cultural traditions. Artists traditionally use natural dyes and pigments derived from plants, flowers, and minerals, and paint on walls, cloth, or handmade paper." ,
    full:
      "Madhubani painting, also known as Mithila art, originated in the Mithila region of Bihar. Traditionally created by women on mud walls, floors, and cloth, this art form depicts scenes from Hindu mythology, nature, and daily life. Natural dyes and pigments are used, making it eco-friendly. Today, Madhubani art has gained international recognition and is practiced on canvas, paper, and fabric.Common themes include scenes from Hindu epics like the Ramayana and Mahabharata, as well as representations of animals, birds, flowers, and daily village life. Madhubani painting is unique for its use of bold lines, geometric patterns, and bright, contrasting colors. Historically, it was practiced mainly by women during festivals, weddings, and religious rituals, making it not only an art form but also a reflection of social and cultural life in Mithila. Today, Madhubani art is recognized globally and has become a symbol of India’s rich folk heritage.Common themes include scenes from Hindu epics like the Ramayana and Mahabharata, as well as representations of animals, birds, flowers, and daily village life. Madhubani painting is unique for its use of bold lines, geometric patterns, and bright, contrasting colors. Historically, it was practiced mainly by women during festivals, weddings, and religious rituals, making it not only an art form but also a reflection of social and cultural life in Mithila. Today, Madhubani art is recognized globally and has become a symbol of India’s rich folk heritage."
  },
  {
    id: 5,
    title: "Sikki Grass Craft",
    image: chana_chat,
    short:
      "Madhubani painting is one of the most famous art forms of Bihar, known for its vibrant colors and mythological themes. lorem ipsum dolor sit amet, consectetur adipiscing elit. Madhubani painting, also known as Mithila art, is a traditional Indian folk art that originates from the Mithila region of Bihar. This art form is characterized by intricate patterns, vibrant colors, and elaborate motifs, often depicting nature, mythology, and cultural traditions. Artists traditionally use natural dyes and pigments derived from plants, flowers, and minerals, and paint on walls, cloth, or handmade paper." ,
    full:
      "Madhubani painting, also known as Mithila art, originated in the Mithila region of Bihar. Traditionally created by women on mud walls, floors, and cloth, this art form depicts scenes from Hindu mythology, nature, and daily life. Natural dyes and pigments are used, making it eco-friendly. Today, Madhubani art has gained international recognition and is practiced on canvas, paper, and fabric.Common themes include scenes from Hindu epics like the Ramayana and Mahabharata, as well as representations of animals, birds, flowers, and daily village life. Madhubani painting is unique for its use of bold lines, geometric patterns, and bright, contrasting colors. Historically, it was practiced mainly by women during festivals, weddings, and religious rituals, making it not only an art form but also a reflection of social and cultural life in Mithila. Today, Madhubani art is recognized globally and has become a symbol of India’s rich folk heritage.Common themes include scenes from Hindu epics like the Ramayana and Mahabharata, as well as representations of animals, birds, flowers, and daily village life. Madhubani painting is unique for its use of bold lines, geometric patterns, and bright, contrasting colors. Historically, it was practiced mainly by women during festivals, weddings, and religious rituals, making it not only an art form but also a reflection of social and cultural life in Mithila. Today, Madhubani art is recognized globally and has become a symbol of India’s rich folk heritage."
  },
  {
    id: 6,
    title: "Sikki Grass Craft",
    image: chana_muri,
    short:
      "Madhubani painting is one of the most famous art forms of Bihar, known for its vibrant colors and mythological themes. lorem ipsum dolor sit amet, consectetur adipiscing elit. Madhubani painting, also known as Mithila art, is a traditional Indian folk art that originates from the Mithila region of Bihar. This art form is characterized by intricate patterns, vibrant colors, and elaborate motifs, often depicting nature, mythology, and cultural traditions. Artists traditionally use natural dyes and pigments derived from plants, flowers, and minerals, and paint on walls, cloth, or handmade paper." ,
    full:
      "Madhubani painting, also known as Mithila art, originated in the Mithila region of Bihar. Traditionally created by women on mud walls, floors, and cloth, this art form depicts scenes from Hindu mythology, nature, and daily life. Natural dyes and pigments are used, making it eco-friendly. Today, Madhubani art has gained international recognition and is practiced on canvas, paper, and fabric.Common themes include scenes from Hindu epics like the Ramayana and Mahabharata, as well as representations of animals, birds, flowers, and daily village life. Madhubani painting is unique for its use of bold lines, geometric patterns, and bright, contrasting colors. Historically, it was practiced mainly by women during festivals, weddings, and religious rituals, making it not only an art form but also a reflection of social and cultural life in Mithila. Today, Madhubani art is recognized globally and has become a symbol of India’s rich folk heritage.Common themes include scenes from Hindu epics like the Ramayana and Mahabharata, as well as representations of animals, birds, flowers, and daily village life. Madhubani painting is unique for its use of bold lines, geometric patterns, and bright, contrasting colors. Historically, it was practiced mainly by women during festivals, weddings, and religious rituals, making it not only an art form but also a reflection of social and cultural life in Mithila. Today, Madhubani art is recognized globally and has become a symbol of India’s rich folk heritage."
  },
  {
    id: 7,
    title: "Sikki Grass Craft",
    image: chandrakala,
    short:
      "Madhubani painting is one of the most famous art forms of Bihar, known for its vibrant colors and mythological themes. lorem ipsum dolor sit amet, consectetur adipiscing elit. Madhubani painting, also known as Mithila art, is a traditional Indian folk art that originates from the Mithila region of Bihar. This art form is characterized by intricate patterns, vibrant colors, and elaborate motifs, often depicting nature, mythology, and cultural traditions. Artists traditionally use natural dyes and pigments derived from plants, flowers, and minerals, and paint on walls, cloth, or handmade paper." ,
    full:
      "Madhubani painting, also known as Mithila art, originated in the Mithila region of Bihar. Traditionally created by women on mud walls, floors, and cloth, this art form depicts scenes from Hindu mythology, nature, and daily life. Natural dyes and pigments are used, making it eco-friendly. Today, Madhubani art has gained international recognition and is practiced on canvas, paper, and fabric.Common themes include scenes from Hindu epics like the Ramayana and Mahabharata, as well as representations of animals, birds, flowers, and daily village life. Madhubani painting is unique for its use of bold lines, geometric patterns, and bright, contrasting colors. Historically, it was practiced mainly by women during festivals, weddings, and religious rituals, making it not only an art form but also a reflection of social and cultural life in Mithila. Today, Madhubani art is recognized globally and has become a symbol of India’s rich folk heritage.Common themes include scenes from Hindu epics like the Ramayana and Mahabharata, as well as representations of animals, birds, flowers, and daily village life. Madhubani painting is unique for its use of bold lines, geometric patterns, and bright, contrasting colors. Historically, it was practiced mainly by women during festivals, weddings, and religious rituals, making it not only an art form but also a reflection of social and cultural life in Mithila. Today, Madhubani art is recognized globally and has become a symbol of India’s rich folk heritage."
  },
  {
    id: 8,
    title: "Sikki Grass Craft",
    image: chicken_chawal,
    short:
      "Madhubani painting is one of the most famous art forms of Bihar, known for its vibrant colors and mythological themes. lorem ipsum dolor sit amet, consectetur adipiscing elit. Madhubani painting, also known as Mithila art, is a traditional Indian folk art that originates from the Mithila region of Bihar. This art form is characterized by intricate patterns, vibrant colors, and elaborate motifs, often depicting nature, mythology, and cultural traditions. Artists traditionally use natural dyes and pigments derived from plants, flowers, and minerals, and paint on walls, cloth, or handmade paper." ,
    full:
      "Madhubani painting, also known as Mithila art, originated in the Mithila region of Bihar. Traditionally created by women on mud walls, floors, and cloth, this art form depicts scenes from Hindu mythology, nature, and daily life. Natural dyes and pigments are used, making it eco-friendly. Today, Madhubani art has gained international recognition and is practiced on canvas, paper, and fabric.Common themes include scenes from Hindu epics like the Ramayana and Mahabharata, as well as representations of animals, birds, flowers, and daily village life. Madhubani painting is unique for its use of bold lines, geometric patterns, and bright, contrasting colors. Historically, it was practiced mainly by women during festivals, weddings, and religious rituals, making it not only an art form but also a reflection of social and cultural life in Mithila. Today, Madhubani art is recognized globally and has become a symbol of India’s rich folk heritage.Common themes include scenes from Hindu epics like the Ramayana and Mahabharata, as well as representations of animals, birds, flowers, and daily village life. Madhubani painting is unique for its use of bold lines, geometric patterns, and bright, contrasting colors. Historically, it was practiced mainly by women during festivals, weddings, and religious rituals, making it not only an art form but also a reflection of social and cultural life in Mithila. Today, Madhubani art is recognized globally and has become a symbol of India’s rich folk heritage."
  },
  {
    id: 9,
    title: "Sikki Grass Craft",
    image: dahi_chuda,
    short:
      "Madhubani painting is one of the most famous art forms of Bihar, known for its vibrant colors and mythological themes. lorem ipsum dolor sit amet, consectetur adipiscing elit. Madhubani painting, also known as Mithila art, is a traditional Indian folk art that originates from the Mithila region of Bihar. This art form is characterized by intricate patterns, vibrant colors, and elaborate motifs, often depicting nature, mythology, and cultural traditions. Artists traditionally use natural dyes and pigments derived from plants, flowers, and minerals, and paint on walls, cloth, or handmade paper." ,
    full:
      "Madhubani painting, also known as Mithila art, originated in the Mithila region of Bihar. Traditionally created by women on mud walls, floors, and cloth, this art form depicts scenes from Hindu mythology, nature, and daily life. Natural dyes and pigments are used, making it eco-friendly. Today, Madhubani art has gained international recognition and is practiced on canvas, paper, and fabric.Common themes include scenes from Hindu epics like the Ramayana and Mahabharata, as well as representations of animals, birds, flowers, and daily village life. Madhubani painting is unique for its use of bold lines, geometric patterns, and bright, contrasting colors. Historically, it was practiced mainly by women during festivals, weddings, and religious rituals, making it not only an art form but also a reflection of social and cultural life in Mithila. Today, Madhubani art is recognized globally and has become a symbol of India’s rich folk heritage.Common themes include scenes from Hindu epics like the Ramayana and Mahabharata, as well as representations of animals, birds, flowers, and daily village life. Madhubani painting is unique for its use of bold lines, geometric patterns, and bright, contrasting colors. Historically, it was practiced mainly by women during festivals, weddings, and religious rituals, making it not only an art form but also a reflection of social and cultural life in Mithila. Today, Madhubani art is recognized globally and has become a symbol of India’s rich folk heritage."
  },
  {
    id: 10,
    title: "Sikki Grass Craft",
    image: daal_puri,
    short:
      "Madhubani painting is one of the most famous art forms of Bihar, known for its vibrant colors and mythological themes. lorem ipsum dolor sit amet, consectetur adipiscing elit. Madhubani painting, also known as Mithila art, is a traditional Indian folk art that originates from the Mithila region of Bihar. This art form is characterized by intricate patterns, vibrant colors, and elaborate motifs, often depicting nature, mythology, and cultural traditions. Artists traditionally use natural dyes and pigments derived from plants, flowers, and minerals, and paint on walls, cloth, or handmade paper." ,
    full:
      "Madhubani painting, also known as Mithila art, originated in the Mithila region of Bihar. Traditionally created by women on mud walls, floors, and cloth, this art form depicts scenes from Hindu mythology, nature, and daily life. Natural dyes and pigments are used, making it eco-friendly. Today, Madhubani art has gained international recognition and is practiced on canvas, paper, and fabric.Common themes include scenes from Hindu epics like the Ramayana and Mahabharata, as well as representations of animals, birds, flowers, and daily village life. Madhubani painting is unique for its use of bold lines, geometric patterns, and bright, contrasting colors. Historically, it was practiced mainly by women during festivals, weddings, and religious rituals, making it not only an art form but also a reflection of social and cultural life in Mithila. Today, Madhubani art is recognized globally and has become a symbol of India’s rich folk heritage.Common themes include scenes from Hindu epics like the Ramayana and Mahabharata, as well as representations of animals, birds, flowers, and daily village life. Madhubani painting is unique for its use of bold lines, geometric patterns, and bright, contrasting colors. Historically, it was practiced mainly by women during festivals, weddings, and religious rituals, making it not only an art form but also a reflection of social and cultural life in Mithila. Today, Madhubani art is recognized globally and has become a symbol of India’s rich folk heritage."
  },
  {
    id: 11,
    title: "Sikki Grass Craft",
    image: fry_chida,
    short:
      "Madhubani painting is one of the most famous art forms of Bihar, known for its vibrant colors and mythological themes. lorem ipsum dolor sit amet, consectetur adipiscing elit. Madhubani painting, also known as Mithila art, is a traditional Indian folk art that originates from the Mithila region of Bihar. This art form is characterized by intricate patterns, vibrant colors, and elaborate motifs, often depicting nature, mythology, and cultural traditions. Artists traditionally use natural dyes and pigments derived from plants, flowers, and minerals, and paint on walls, cloth, or handmade paper." ,
    full:
      "Madhubani painting, also known as Mithila art, originated in the Mithila region of Bihar. Traditionally created by women on mud walls, floors, and cloth, this art form depicts scenes from Hindu mythology, nature, and daily life. Natural dyes and pigments are used, making it eco-friendly. Today, Madhubani art has gained international recognition and is practiced on canvas, paper, and fabric.Common themes include scenes from Hindu epics like the Ramayana and Mahabharata, as well as representations of animals, birds, flowers, and daily village life. Madhubani painting is unique for its use of bold lines, geometric patterns, and bright, contrasting colors. Historically, it was practiced mainly by women during festivals, weddings, and religious rituals, making it not only an art form but also a reflection of social and cultural life in Mithila. Today, Madhubani art is recognized globally and has become a symbol of India’s rich folk heritage.Common themes include scenes from Hindu epics like the Ramayana and Mahabharata, as well as representations of animals, birds, flowers, and daily village life. Madhubani painting is unique for its use of bold lines, geometric patterns, and bright, contrasting colors. Historically, it was practiced mainly by women during festivals, weddings, and religious rituals, making it not only an art form but also a reflection of social and cultural life in Mithila. Today, Madhubani art is recognized globally and has become a symbol of India’s rich folk heritage."
  },
  {
    id: 12,
    title: "Sikki Grass Craft",
    image: handi_mutton,
    short:
      "Madhubani painting is one of the most famous art forms of Bihar, known for its vibrant colors and mythological themes. lorem ipsum dolor sit amet, consectetur adipiscing elit. Madhubani painting, also known as Mithila art, is a traditional Indian folk art that originates from the Mithila region of Bihar. This art form is characterized by intricate patterns, vibrant colors, and elaborate motifs, often depicting nature, mythology, and cultural traditions. Artists traditionally use natural dyes and pigments derived from plants, flowers, and minerals, and paint on walls, cloth, or handmade paper." ,
    full:
      "Madhubani painting, also known as Mithila art, originated in the Mithila region of Bihar. Traditionally created by women on mud walls, floors, and cloth, this art form depicts scenes from Hindu mythology, nature, and daily life. Natural dyes and pigments are used, making it eco-friendly. Today, Madhubani art has gained international recognition and is practiced on canvas, paper, and fabric.Common themes include scenes from Hindu epics like the Ramayana and Mahabharata, as well as representations of animals, birds, flowers, and daily village life. Madhubani painting is unique for its use of bold lines, geometric patterns, and bright, contrasting colors. Historically, it was practiced mainly by women during festivals, weddings, and religious rituals, making it not only an art form but also a reflection of social and cultural life in Mithila. Today, Madhubani art is recognized globally and has become a symbol of India’s rich folk heritage.Common themes include scenes from Hindu epics like the Ramayana and Mahabharata, as well as representations of animals, birds, flowers, and daily village life. Madhubani painting is unique for its use of bold lines, geometric patterns, and bright, contrasting colors. Historically, it was practiced mainly by women during festivals, weddings, and religious rituals, making it not only an art form but also a reflection of social and cultural life in Mithila. Today, Madhubani art is recognized globally and has become a symbol of India’s rich folk heritage."
  },
  {
    id: 13,
    title: "Sikki Grass Craft",
    image: jhalmuri,
    short:
      "Madhubani painting is one of the most famous art forms of Bihar, known for its vibrant colors and mythological themes. lorem ipsum dolor sit amet, consectetur adipiscing elit. Madhubani painting, also known as Mithila art, is a traditional Indian folk art that originates from the Mithila region of Bihar. This art form is characterized by intricate patterns, vibrant colors, and elaborate motifs, often depicting nature, mythology, and cultural traditions. Artists traditionally use natural dyes and pigments derived from plants, flowers, and minerals, and paint on walls, cloth, or handmade paper." ,
    full:
      "Madhubani painting, also known as Mithila art, originated in the Mithila region of Bihar. Traditionally created by women on mud walls, floors, and cloth, this art form depicts scenes from Hindu mythology, nature, and daily life. Natural dyes and pigments are used, making it eco-friendly. Today, Madhubani art has gained international recognition and is practiced on canvas, paper, and fabric.Common themes include scenes from Hindu epics like the Ramayana and Mahabharata, as well as representations of animals, birds, flowers, and daily village life. Madhubani painting is unique for its use of bold lines, geometric patterns, and bright, contrasting colors. Historically, it was practiced mainly by women during festivals, weddings, and religious rituals, making it not only an art form but also a reflection of social and cultural life in Mithila. Today, Madhubani art is recognized globally and has become a symbol of India’s rich folk heritage.Common themes include scenes from Hindu epics like the Ramayana and Mahabharata, as well as representations of animals, birds, flowers, and daily village life. Madhubani painting is unique for its use of bold lines, geometric patterns, and bright, contrasting colors. Historically, it was practiced mainly by women during festivals, weddings, and religious rituals, making it not only an art form but also a reflection of social and cultural life in Mithila. Today, Madhubani art is recognized globally and has become a symbol of India’s rich folk heritage."
  },
  {
    id: 14,
    title: "Sikki Grass Craft",
    image: khichdi,
    short:
      "Madhubani painting is one of the most famous art forms of Bihar, known for its vibrant colors and mythological themes. lorem ipsum dolor sit amet, consectetur adipiscing elit. Madhubani painting, also known as Mithila art, is a traditional Indian folk art that originates from the Mithila region of Bihar. This art form is characterized by intricate patterns, vibrant colors, and elaborate motifs, often depicting nature, mythology, and cultural traditions. Artists traditionally use natural dyes and pigments derived from plants, flowers, and minerals, and paint on walls, cloth, or handmade paper." ,
    full:
      "Madhubani painting, also known as Mithila art, originated in the Mithila region of Bihar. Traditionally created by women on mud walls, floors, and cloth, this art form depicts scenes from Hindu mythology, nature, and daily life. Natural dyes and pigments are used, making it eco-friendly. Today, Madhubani art has gained international recognition and is practiced on canvas, paper, and fabric.Common themes include scenes from Hindu epics like the Ramayana and Mahabharata, as well as representations of animals, birds, flowers, and daily village life. Madhubani painting is unique for its use of bold lines, geometric patterns, and bright, contrasting colors. Historically, it was practiced mainly by women during festivals, weddings, and religious rituals, making it not only an art form but also a reflection of social and cultural life in Mithila. Today, Madhubani art is recognized globally and has become a symbol of India’s rich folk heritage.Common themes include scenes from Hindu epics like the Ramayana and Mahabharata, as well as representations of animals, birds, flowers, and daily village life. Madhubani painting is unique for its use of bold lines, geometric patterns, and bright, contrasting colors. Historically, it was practiced mainly by women during festivals, weddings, and religious rituals, making it not only an art form but also a reflection of social and cultural life in Mithila. Today, Madhubani art is recognized globally and has become a symbol of India’s rich folk heritage."
  },
  {
    id: 15,
    title: "Sikki Grass Craft",
    image: machi_chawal,
    short:
      "Madhubani painting is one of the most famous art forms of Bihar, known for its vibrant colors and mythological themes. lorem ipsum dolor sit amet, consectetur adipiscing elit. Madhubani painting, also known as Mithila art, is a traditional Indian folk art that originates from the Mithila region of Bihar. This art form is characterized by intricate patterns, vibrant colors, and elaborate motifs, often depicting nature, mythology, and cultural traditions. Artists traditionally use natural dyes and pigments derived from plants, flowers, and minerals, and paint on walls, cloth, or handmade paper." ,
    full:
      "Madhubani painting, also known as Mithila art, originated in the Mithila region of Bihar. Traditionally created by women on mud walls, floors, and cloth, this art form depicts scenes from Hindu mythology, nature, and daily life. Natural dyes and pigments are used, making it eco-friendly. Today, Madhubani art has gained international recognition and is practiced on canvas, paper, and fabric.Common themes include scenes from Hindu epics like the Ramayana and Mahabharata, as well as representations of animals, birds, flowers, and daily village life. Madhubani painting is unique for its use of bold lines, geometric patterns, and bright, contrasting colors. Historically, it was practiced mainly by women during festivals, weddings, and religious rituals, making it not only an art form but also a reflection of social and cultural life in Mithila. Today, Madhubani art is recognized globally and has become a symbol of India’s rich folk heritage.Common themes include scenes from Hindu epics like the Ramayana and Mahabharata, as well as representations of animals, birds, flowers, and daily village life. Madhubani painting is unique for its use of bold lines, geometric patterns, and bright, contrasting colors. Historically, it was practiced mainly by women during festivals, weddings, and religious rituals, making it not only an art form but also a reflection of social and cultural life in Mithila. Today, Madhubani art is recognized globally and has become a symbol of India’s rich folk heritage."
  },
  {
    id: 16,
    title: "Sikki Grass Craft",
    image: malpua,
    short:
      "Madhubani painting is one of the most famous art forms of Bihar, known for its vibrant colors and mythological themes. lorem ipsum dolor sit amet, consectetur adipiscing elit. Madhubani painting, also known as Mithila art, is a traditional Indian folk art that originates from the Mithila region of Bihar. This art form is characterized by intricate patterns, vibrant colors, and elaborate motifs, often depicting nature, mythology, and cultural traditions. Artists traditionally use natural dyes and pigments derived from plants, flowers, and minerals, and paint on walls, cloth, or handmade paper." ,
    full:
      "Madhubani painting, also known as Mithila art, originated in the Mithila region of Bihar. Traditionally created by women on mud walls, floors, and cloth, this art form depicts scenes from Hindu mythology, nature, and daily life. Natural dyes and pigments are used, making it eco-friendly. Today, Madhubani art has gained international recognition and is practiced on canvas, paper, and fabric.Common themes include scenes from Hindu epics like the Ramayana and Mahabharata, as well as representations of animals, birds, flowers, and daily village life. Madhubani painting is unique for its use of bold lines, geometric patterns, and bright, contrasting colors. Historically, it was practiced mainly by women during festivals, weddings, and religious rituals, making it not only an art form but also a reflection of social and cultural life in Mithila. Today, Madhubani art is recognized globally and has become a symbol of India’s rich folk heritage.Common themes include scenes from Hindu epics like the Ramayana and Mahabharata, as well as representations of animals, birds, flowers, and daily village life. Madhubani painting is unique for its use of bold lines, geometric patterns, and bright, contrasting colors. Historically, it was practiced mainly by women during festivals, weddings, and religious rituals, making it not only an art form but also a reflection of social and cultural life in Mithila. Today, Madhubani art is recognized globally and has become a symbol of India’s rich folk heritage."
  },
  {
    id: 17,
    title: "Sikki Grass Craft",
    image: rasgulla,
    short:
      "Madhubani painting is one of the most famous art forms of Bihar, known for its vibrant colors and mythological themes. lorem ipsum dolor sit amet, consectetur adipiscing elit. Madhubani painting, also known as Mithila art, is a traditional Indian folk art that originates from the Mithila region of Bihar. This art form is characterized by intricate patterns, vibrant colors, and elaborate motifs, often depicting nature, mythology, and cultural traditions. Artists traditionally use natural dyes and pigments derived from plants, flowers, and minerals, and paint on walls, cloth, or handmade paper." ,
    full:
      "Madhubani painting, also known as Mithila art, originated in the Mithila region of Bihar. Traditionally created by women on mud walls, floors, and cloth, this art form depicts scenes from Hindu mythology, nature, and daily life. Natural dyes and pigments are used, making it eco-friendly. Today, Madhubani art has gained international recognition and is practiced on canvas, paper, and fabric.Common themes include scenes from Hindu epics like the Ramayana and Mahabharata, as well as representations of animals, birds, flowers, and daily village life. Madhubani painting is unique for its use of bold lines, geometric patterns, and bright, contrasting colors. Historically, it was practiced mainly by women during festivals, weddings, and religious rituals, making it not only an art form but also a reflection of social and cultural life in Mithila. Today, Madhubani art is recognized globally and has become a symbol of India’s rich folk heritage.Common themes include scenes from Hindu epics like the Ramayana and Mahabharata, as well as representations of animals, birds, flowers, and daily village life. Madhubani painting is unique for its use of bold lines, geometric patterns, and bright, contrasting colors. Historically, it was practiced mainly by women during festivals, weddings, and religious rituals, making it not only an art form but also a reflection of social and cultural life in Mithila. Today, Madhubani art is recognized globally and has become a symbol of India’s rich folk heritage."
  },
  {
    id: 18,
    title: "Sikki Grass Craft",
    image: sattu_paratha,
    short:
      "Madhubani painting is one of the most famous art forms of Bihar, known for its vibrant colors and mythological themes. lorem ipsum dolor sit amet, consectetur adipiscing elit. Madhubani painting, also known as Mithila art, is a traditional Indian folk art that originates from the Mithila region of Bihar. This art form is characterized by intricate patterns, vibrant colors, and elaborate motifs, often depicting nature, mythology, and cultural traditions. Artists traditionally use natural dyes and pigments derived from plants, flowers, and minerals, and paint on walls, cloth, or handmade paper." ,
    full:
      "Madhubani painting, also known as Mithila art, originated in the Mithila region of Bihar. Traditionally created by women on mud walls, floors, and cloth, this art form depicts scenes from Hindu mythology, nature, and daily life. Natural dyes and pigments are used, making it eco-friendly. Today, Madhubani art has gained international recognition and is practiced on canvas, paper, and fabric.Common themes include scenes from Hindu epics like the Ramayana and Mahabharata, as well as representations of animals, birds, flowers, and daily village life. Madhubani painting is unique for its use of bold lines, geometric patterns, and bright, contrasting colors. Historically, it was practiced mainly by women during festivals, weddings, and religious rituals, making it not only an art form but also a reflection of social and cultural life in Mithila. Today, Madhubani art is recognized globally and has become a symbol of India’s rich folk heritage.Common themes include scenes from Hindu epics like the Ramayana and Mahabharata, as well as representations of animals, birds, flowers, and daily village life. Madhubani painting is unique for its use of bold lines, geometric patterns, and bright, contrasting colors. Historically, it was practiced mainly by women during festivals, weddings, and religious rituals, making it not only an art form but also a reflection of social and cultural life in Mithila. Today, Madhubani art is recognized globally and has become a symbol of India’s rich folk heritage."
  },
  {
    id: 19,
    title: "Sikki Grass Craft",
    image: sewai,
    short:
      "Madhubani painting is one of the most famous art forms of Bihar, known for its vibrant colors and mythological themes. lorem ipsum dolor sit amet, consectetur adipiscing elit. Madhubani painting, also known as Mithila art, is a traditional Indian folk art that originates from the Mithila region of Bihar. This art form is characterized by intricate patterns, vibrant colors, and elaborate motifs, often depicting nature, mythology, and cultural traditions. Artists traditionally use natural dyes and pigments derived from plants, flowers, and minerals, and paint on walls, cloth, or handmade paper." ,
    full:
      "Madhubani painting, also known as Mithila art, originated in the Mithila region of Bihar. Traditionally created by women on mud walls, floors, and cloth, this art form depicts scenes from Hindu mythology, nature, and daily life. Natural dyes and pigments are used, making it eco-friendly. Today, Madhubani art has gained international recognition and is practiced on canvas, paper, and fabric.Common themes include scenes from Hindu epics like the Ramayana and Mahabharata, as well as representations of animals, birds, flowers, and daily village life. Madhubani painting is unique for its use of bold lines, geometric patterns, and bright, contrasting colors. Historically, it was practiced mainly by women during festivals, weddings, and religious rituals, making it not only an art form but also a reflection of social and cultural life in Mithila. Today, Madhubani art is recognized globally and has become a symbol of India’s rich folk heritage.Common themes include scenes from Hindu epics like the Ramayana and Mahabharata, as well as representations of animals, birds, flowers, and daily village life. Madhubani painting is unique for its use of bold lines, geometric patterns, and bright, contrasting colors. Historically, it was practiced mainly by women during festivals, weddings, and religious rituals, making it not only an art form but also a reflection of social and cultural life in Mithila. Today, Madhubani art is recognized globally and has become a symbol of India’s rich folk heritage."
  },
  {
    id: 20,
    title: "Sheer_khurma",
    image: sheer_khurma,
    short:
      "Madhubani painting is one of the most famous art forms of Bihar, known for its vibrant colors and mythological themes. lorem ipsum dolor sit amet, consectetur adipiscing elit. Madhubani painting, also known as Mithila art, is a traditional Indian folk art that originates from the Mithila region of Bihar. This art form is characterized by intricate patterns, vibrant colors, and elaborate motifs, often depicting nature, mythology, and cultural traditions. Artists traditionally use natural dyes and pigments derived from plants, flowers, and minerals, and paint on walls, cloth, or handmade paper." ,
    full:
      "Madhubani painting, also known as Mithila art, originated in the Mithila region of Bihar. Traditionally created by women on mud walls, floors, and cloth, this art form depicts scenes from Hindu mythology, nature, and daily life. Natural dyes and pigments are used, making it eco-friendly. Today, Madhubani art has gained international recognition and is practiced on canvas, paper, and fabric.Common themes include scenes from Hindu epics like the Ramayana and Mahabharata, as well as representations of animals, birds, flowers, and daily village life. Madhubani painting is unique for its use of bold lines, geometric patterns, and bright, contrasting colors. Historically, it was practiced mainly by women during festivals, weddings, and religious rituals, making it not only an art form but also a reflection of social and cultural life in Mithila. Today, Madhubani art is recognized globally and has become a symbol of India’s rich folk heritage.Common themes include scenes from Hindu epics like the Ramayana and Mahabharata, as well as representations of animals, birds, flowers, and daily village life. Madhubani painting is unique for its use of bold lines, geometric patterns, and bright, contrasting colors. Historically, it was practiced mainly by women during festivals, weddings, and religious rituals, making it not only an art form but also a reflection of social and cultural life in Mithila. Today, Madhubani art is recognized globally and has become a symbol of India’s rich folk heritage."
  },
  {
    id: 21,
    title: "Sikki Grass Craft",
    image: aloobhujiya,
    short:
      "Madhubani painting is one of the most famous art forms of Bihar, known for its vibrant colors and mythological themes. lorem ipsum dolor sit amet, consectetur adipiscing elit. Madhubani painting, also known as Mithila art, is a traditional Indian folk art that originates from the Mithila region of Bihar. This art form is characterized by intricate patterns, vibrant colors, and elaborate motifs, often depicting nature, mythology, and cultural traditions. Artists traditionally use natural dyes and pigments derived from plants, flowers, and minerals, and paint on walls, cloth, or handmade paper." ,
    full:
      "Madhubani painting, also known as Mithila art, originated in the Mithila region of Bihar. Traditionally created by women on mud walls, floors, and cloth, this art form depicts scenes from Hindu mythology, nature, and daily life. Natural dyes and pigments are used, making it eco-friendly. Today, Madhubani art has gained international recognition and is practiced on canvas, paper, and fabric.Common themes include scenes from Hindu epics like the Ramayana and Mahabharata, as well as representations of animals, birds, flowers, and daily village life. Madhubani painting is unique for its use of bold lines, geometric patterns, and bright, contrasting colors. Historically, it was practiced mainly by women during festivals, weddings, and religious rituals, making it not only an art form but also a reflection of social and cultural life in Mithila. Today, Madhubani art is recognized globally and has become a symbol of India’s rich folk heritage.Common themes include scenes from Hindu epics like the Ramayana and Mahabharata, as well as representations of animals, birds, flowers, and daily village life. Madhubani painting is unique for its use of bold lines, geometric patterns, and bright, contrasting colors. Historically, it was practiced mainly by women during festivals, weddings, and religious rituals, making it not only an art form but also a reflection of social and cultural life in Mithila. Today, Madhubani art is recognized globally and has become a symbol of India’s rich folk heritage."
  }
//   {
//     id: 10,
//     title: "Sikki Grass Craft",
//     image: daal_puri,
//     short:
//       "Madhubani painting is one of the most famous art forms of Bihar, known for its vibrant colors and mythological themes. lorem ipsum dolor sit amet, consectetur adipiscing elit. Madhubani painting, also known as Mithila art, is a traditional Indian folk art that originates from the Mithila region of Bihar. This art form is characterized by intricate patterns, vibrant colors, and elaborate motifs, often depicting nature, mythology, and cultural traditions. Artists traditionally use natural dyes and pigments derived from plants, flowers, and minerals, and paint on walls, cloth, or handmade paper." ,
//     full:
//       "Madhubani painting, also known as Mithila art, originated in the Mithila region of Bihar. Traditionally created by women on mud walls, floors, and cloth, this art form depicts scenes from Hindu mythology, nature, and daily life. Natural dyes and pigments are used, making it eco-friendly. Today, Madhubani art has gained international recognition and is practiced on canvas, paper, and fabric.Common themes include scenes from Hindu epics like the Ramayana and Mahabharata, as well as representations of animals, birds, flowers, and daily village life. Madhubani painting is unique for its use of bold lines, geometric patterns, and bright, contrasting colors. Historically, it was practiced mainly by women during festivals, weddings, and religious rituals, making it not only an art form but also a reflection of social and cultural life in Mithila. Today, Madhubani art is recognized globally and has become a symbol of India’s rich folk heritage.Common themes include scenes from Hindu epics like the Ramayana and Mahabharata, as well as representations of animals, birds, flowers, and daily village life. Madhubani painting is unique for its use of bold lines, geometric patterns, and bright, contrasting colors. Historically, it was practiced mainly by women during festivals, weddings, and religious rituals, making it not only an art form but also a reflection of social and cultural life in Mithila. Today, Madhubani art is recognized globally and has become a symbol of India’s rich folk heritage."
//   },
//   {
//     id: 10,
//     title: "Sikki Grass Craft",
//     image: daal_puri,
//     short:
//       "Madhubani painting is one of the most famous art forms of Bihar, known for its vibrant colors and mythological themes. lorem ipsum dolor sit amet, consectetur adipiscing elit. Madhubani painting, also known as Mithila art, is a traditional Indian folk art that originates from the Mithila region of Bihar. This art form is characterized by intricate patterns, vibrant colors, and elaborate motifs, often depicting nature, mythology, and cultural traditions. Artists traditionally use natural dyes and pigments derived from plants, flowers, and minerals, and paint on walls, cloth, or handmade paper." ,
//     full:
//       "Madhubani painting, also known as Mithila art, originated in the Mithila region of Bihar. Traditionally created by women on mud walls, floors, and cloth, this art form depicts scenes from Hindu mythology, nature, and daily life. Natural dyes and pigments are used, making it eco-friendly. Today, Madhubani art has gained international recognition and is practiced on canvas, paper, and fabric.Common themes include scenes from Hindu epics like the Ramayana and Mahabharata, as well as representations of animals, birds, flowers, and daily village life. Madhubani painting is unique for its use of bold lines, geometric patterns, and bright, contrasting colors. Historically, it was practiced mainly by women during festivals, weddings, and religious rituals, making it not only an art form but also a reflection of social and cultural life in Mithila. Today, Madhubani art is recognized globally and has become a symbol of India’s rich folk heritage.Common themes include scenes from Hindu epics like the Ramayana and Mahabharata, as well as representations of animals, birds, flowers, and daily village life. Madhubani painting is unique for its use of bold lines, geometric patterns, and bright, contrasting colors. Historically, it was practiced mainly by women during festivals, weddings, and religious rituals, making it not only an art form but also a reflection of social and cultural life in Mithila. Today, Madhubani art is recognized globally and has become a symbol of India’s rich folk heritage."
//   },
//   {
//     id: 10,
//     title: "Sikki Grass Craft",
//     image: daal_puri,
//     short:
//       "Madhubani painting is one of the most famous art forms of Bihar, known for its vibrant colors and mythological themes. lorem ipsum dolor sit amet, consectetur adipiscing elit. Madhubani painting, also known as Mithila art, is a traditional Indian folk art that originates from the Mithila region of Bihar. This art form is characterized by intricate patterns, vibrant colors, and elaborate motifs, often depicting nature, mythology, and cultural traditions. Artists traditionally use natural dyes and pigments derived from plants, flowers, and minerals, and paint on walls, cloth, or handmade paper." ,
//     full:
//       "Madhubani painting, also known as Mithila art, originated in the Mithila region of Bihar. Traditionally created by women on mud walls, floors, and cloth, this art form depicts scenes from Hindu mythology, nature, and daily life. Natural dyes and pigments are used, making it eco-friendly. Today, Madhubani art has gained international recognition and is practiced on canvas, paper, and fabric.Common themes include scenes from Hindu epics like the Ramayana and Mahabharata, as well as representations of animals, birds, flowers, and daily village life. Madhubani painting is unique for its use of bold lines, geometric patterns, and bright, contrasting colors. Historically, it was practiced mainly by women during festivals, weddings, and religious rituals, making it not only an art form but also a reflection of social and cultural life in Mithila. Today, Madhubani art is recognized globally and has become a symbol of India’s rich folk heritage.Common themes include scenes from Hindu epics like the Ramayana and Mahabharata, as well as representations of animals, birds, flowers, and daily village life. Madhubani painting is unique for its use of bold lines, geometric patterns, and bright, contrasting colors. Historically, it was practiced mainly by women during festivals, weddings, and religious rituals, making it not only an art form but also a reflection of social and cultural life in Mithila. Today, Madhubani art is recognized globally and has become a symbol of India’s rich folk heritage."
//   },
//   {
//     id: 10,
//     title: "Sikki Grass Craft",
//     image: daal_puri,
//     short:
//       "Madhubani painting is one of the most famous art forms of Bihar, known for its vibrant colors and mythological themes. lorem ipsum dolor sit amet, consectetur adipiscing elit. Madhubani painting, also known as Mithila art, is a traditional Indian folk art that originates from the Mithila region of Bihar. This art form is characterized by intricate patterns, vibrant colors, and elaborate motifs, often depicting nature, mythology, and cultural traditions. Artists traditionally use natural dyes and pigments derived from plants, flowers, and minerals, and paint on walls, cloth, or handmade paper." ,
//     full:
//       "Madhubani painting, also known as Mithila art, originated in the Mithila region of Bihar. Traditionally created by women on mud walls, floors, and cloth, this art form depicts scenes from Hindu mythology, nature, and daily life. Natural dyes and pigments are used, making it eco-friendly. Today, Madhubani art has gained international recognition and is practiced on canvas, paper, and fabric.Common themes include scenes from Hindu epics like the Ramayana and Mahabharata, as well as representations of animals, birds, flowers, and daily village life. Madhubani painting is unique for its use of bold lines, geometric patterns, and bright, contrasting colors. Historically, it was practiced mainly by women during festivals, weddings, and religious rituals, making it not only an art form but also a reflection of social and cultural life in Mithila. Today, Madhubani art is recognized globally and has become a symbol of India’s rich folk heritage.Common themes include scenes from Hindu epics like the Ramayana and Mahabharata, as well as representations of animals, birds, flowers, and daily village life. Madhubani painting is unique for its use of bold lines, geometric patterns, and bright, contrasting colors. Historically, it was practiced mainly by women during festivals, weddings, and religious rituals, making it not only an art form but also a reflection of social and cultural life in Mithila. Today, Madhubani art is recognized globally and has become a symbol of India’s rich folk heritage."
//   },
//   {
//     id: 10,
//     title: "Sikki Grass Craft",
//     image: daal_puri,
//     short:
//       "Madhubani painting is one of the most famous art forms of Bihar, known for its vibrant colors and mythological themes. lorem ipsum dolor sit amet, consectetur adipiscing elit. Madhubani painting, also known as Mithila art, is a traditional Indian folk art that originates from the Mithila region of Bihar. This art form is characterized by intricate patterns, vibrant colors, and elaborate motifs, often depicting nature, mythology, and cultural traditions. Artists traditionally use natural dyes and pigments derived from plants, flowers, and minerals, and paint on walls, cloth, or handmade paper." ,
//     full:
//       "Madhubani painting, also known as Mithila art, originated in the Mithila region of Bihar. Traditionally created by women on mud walls, floors, and cloth, this art form depicts scenes from Hindu mythology, nature, and daily life. Natural dyes and pigments are used, making it eco-friendly. Today, Madhubani art has gained international recognition and is practiced on canvas, paper, and fabric.Common themes include scenes from Hindu epics like the Ramayana and Mahabharata, as well as representations of animals, birds, flowers, and daily village life. Madhubani painting is unique for its use of bold lines, geometric patterns, and bright, contrasting colors. Historically, it was practiced mainly by women during festivals, weddings, and religious rituals, making it not only an art form but also a reflection of social and cultural life in Mithila. Today, Madhubani art is recognized globally and has become a symbol of India’s rich folk heritage.Common themes include scenes from Hindu epics like the Ramayana and Mahabharata, as well as representations of animals, birds, flowers, and daily village life. Madhubani painting is unique for its use of bold lines, geometric patterns, and bright, contrasting colors. Historically, it was practiced mainly by women during festivals, weddings, and religious rituals, making it not only an art form but also a reflection of social and cultural life in Mithila. Today, Madhubani art is recognized globally and has become a symbol of India’s rich folk heritage."
//   },
//   {
//     id: 10,
//     title: "Sikki Grass Craft",
//     image: daal_puri,
//     short:
//       "Madhubani painting is one of the most famous art forms of Bihar, known for its vibrant colors and mythological themes. lorem ipsum dolor sit amet, consectetur adipiscing elit. Madhubani painting, also known as Mithila art, is a traditional Indian folk art that originates from the Mithila region of Bihar. This art form is characterized by intricate patterns, vibrant colors, and elaborate motifs, often depicting nature, mythology, and cultural traditions. Artists traditionally use natural dyes and pigments derived from plants, flowers, and minerals, and paint on walls, cloth, or handmade paper." ,
//     full:
//       "Madhubani painting, also known as Mithila art, originated in the Mithila region of Bihar. Traditionally created by women on mud walls, floors, and cloth, this art form depicts scenes from Hindu mythology, nature, and daily life. Natural dyes and pigments are used, making it eco-friendly. Today, Madhubani art has gained international recognition and is practiced on canvas, paper, and fabric.Common themes include scenes from Hindu epics like the Ramayana and Mahabharata, as well as representations of animals, birds, flowers, and daily village life. Madhubani painting is unique for its use of bold lines, geometric patterns, and bright, contrasting colors. Historically, it was practiced mainly by women during festivals, weddings, and religious rituals, making it not only an art form but also a reflection of social and cultural life in Mithila. Today, Madhubani art is recognized globally and has become a symbol of India’s rich folk heritage.Common themes include scenes from Hindu epics like the Ramayana and Mahabharata, as well as representations of animals, birds, flowers, and daily village life. Madhubani painting is unique for its use of bold lines, geometric patterns, and bright, contrasting colors. Historically, it was practiced mainly by women during festivals, weddings, and religious rituals, making it not only an art form but also a reflection of social and cultural life in Mithila. Today, Madhubani art is recognized globally and has become a symbol of India’s rich folk heritage."
//   }
    ];

export default foodData;
